/*! Fluent Globe - v0.1.0 - 2014
* http://fluentglobe.com
* Copyright (c) 2014 Henrik Vendelbo; Licensed  */
(function(){var e,f=function(k,g){return function(){return k.apply(g,arguments)}},c={}.hasOwnProperty;e=function(){function k(){this.patch_apply_with_offsets=f(this.patch_apply_with_offsets,this);this.transform_object_diff=f(this.transform_object_diff,this);this.transform_list_diff_dmp=f(this.transform_list_diff_dmp,this);this.transform_list_diff=f(this.transform_list_diff,this);this.apply_diff=f(this.apply_diff,this);this.apply_object_diff_with_offsets=f(this.apply_object_diff_with_offsets,this);
this.apply_object_diff=f(this.apply_object_diff,this);this.apply_list_diff_dmp=f(this.apply_list_diff_dmp,this);this.apply_list_diff=f(this.apply_list_diff,this);this.diff=f(this.diff,this);this.object_diff=f(this.object_diff,this);this._text_to_array=f(this._text_to_array,this);this._serialize_to_text=f(this._serialize_to_text,this);this.list_diff_dmp=f(this.list_diff_dmp,this);this.list_diff=f(this.list_diff,this);this._common_suffix=f(this._common_suffix,this);this._common_prefix=f(this._common_prefix,
this);this.object_equals=f(this.object_equals,this);this.list_equals=f(this.list_equals,this);this.equals=f(this.equals,this);this.deepCopy=f(this.deepCopy,this);this.typeOf=f(this.typeOf,this);this.entries=f(this.entries,this);this.dmp=new diff_match_patch}k.prototype.entries=function(g){var d,a;a=0;for(d in g)c.call(g,d)&&a++;return a};k.prototype.typeOf=function(g){var d;d=typeof g;if(d==="object")if(g){if(typeof g.length==="number"&&typeof g.splice==="function"&&!g.propertyIsEnumerable("length"))d=
"array"}else d="null";return d};k.prototype.deepCopy=function(g){return JSON.parse(JSON.stringify(g))};k.prototype.equals=function(g,d){var a,b;a=this.typeOf(g);b=this.typeOf(d);if(a==="boolean"&&b==="number")return Number(g)===d;if(a==="number"&&b==="boolean")return Number(d)===g;if(a!==b)return false;return a==="array"?this.list_equals(g,d):a==="object"?this.object_equals(g,d):g===d};k.prototype.list_equals=function(g,d){var a,b,h;a=g.length;if(a!==d.length)return false;for(b=h=0;0<=a?h<a:h>a;b=
0<=a?++h:--h)if(!this.equals(g[b],d[b]))return false;return true};k.prototype.object_equals=function(g,d){for(var a in g)if(c.call(g,a)){if(!(a in d))return false;if(!this.equals(g[a],d[a]))return false}for(a in d)if(c.call(d,a))if(!(a in g))return false;return true};k.prototype._common_prefix=function(g,d){var a,b,h;b=Math.min(g.length,d.length);for(a=h=0;0<=b?h<b:h>b;a=0<=b?++h:--h)if(!this.equals(g[a],d[a]))return a;return b};k.prototype._common_suffix=function(g,d){var a,b,h,j,m;b=g.length;h=
d.length;j=Math.min(g.length,d.length);if(j===0)return 0;for(a=m=0;0<=j?m<j:m>j;a=0<=j?++m:--m)if(!this.equals(g[b-a-1],d[h-a-1]))return a;return j};k.prototype.list_diff=function(g,d,a){var b,h,j,m,p,q,s;a=a!=null&&"item"in a?a.item:null;b={};j=g.length;m=d.length;q=this._common_prefix(g,d);h=this._common_suffix(g,d);g=g.slice(q,j-h);d=d.slice(q,m-h);j=g.length;m=d.length;p=Math.max(j,m);for(h=s=0;0<=p?s<=p:s>=p;h=0<=p?++s:--s)if(h<j&&h<m)this.equals(g[h],d[h])||(b[h+q]=this.diff(g[h],d[h],a));else if(h<
j)b[h+q]={o:"-"};else if(h<m)b[h+q]={o:"+",v:d[h]};return b};k.prototype.list_diff_dmp=function(g,d){var a,b;a=this._serialize_to_text(g);b=this._serialize_to_text(d);a=this.dmp.diff_lineMode_(a,b);this.dmp.diff_cleanupEfficiency(a);return this.dmp.diff_toDelta(a)};k.prototype._serialize_to_text=function(g){var d,a,b,h;a="";b=0;for(h=g.length;b<h;b++){d=g[b];a+=""+JSON.stringify(d)+"\n"}return a};k.prototype._text_to_array=function(g){var d,a,b;d=[];a=g.split("\n");return d=function(){var h,j,m;m=
[];h=0;for(j=a.length;h<j;h++){b=a[h];b.length>0&&m.push(JSON.parse(b))}return m}()};k.prototype.object_diff=function(g,d,a){var b,h,j;b={};if(a!=null&&"attributes"in a)a=a.attributes;if(g==null||d==null)return{};for(h in g)if(c.call(g,h)){j=a!=null&&h in a?a[h]:null;if(h in d)this.equals(g[h],d[h])||(b[h]=this.diff(g[h],d[h],j));else b[h]={o:"-"}}for(h in d)if(c.call(d,h))if(!(h in g)&&d[h]!=null)b[h]={o:"+",v:d[h]};return b};k.prototype.diff=function(g,d,a){var b;if(this.equals(g,d))return{};if(a!=
null&&"attributes"in a)a=a.attributes;if(a!=null&&"otype"in a){b=a.otype;switch(b){case "replace":return{o:"r",v:d};case "list":return{o:"L",v:this.list_diff(g,d,a)};case "list_dmp":return{o:"dL",v:this.list_diff_dmp(g,d,a)};case "integer":return{o:"I",v:d-g};case "string":b=this.dmp.diff_main(g,d);b.length>2&&this.dmp.diff_cleanupEfficiency(b);if(b.length>0)return{o:"d",v:this.dmp.diff_toDelta(b)}}}b=this.typeOf(g);if(b!==this.typeOf(d))return{o:"r",v:d};switch(b){case "boolean":return{o:"r",v:d};
case "number":return{o:"r",v:d};case "array":return{o:"r",v:d};case "object":return{o:"O",v:this.object_diff(g,d,a)};case "string":b=this.dmp.diff_main(g,d);b.length>2&&this.dmp.diff_cleanupEfficiency(b);if(b.length>0)return{o:"d",v:this.dmp.diff_toDelta(b)}}return{}};k.prototype.apply_list_diff=function(g,d){var a,b,h,j,m,p,q,s,w;p=this.deepCopy(g);j=[];a=[];for(m in d)if(c.call(d,m)){j.push(m);j.sort()}m=0;for(w=j.length;m<w;m++){h=j[m];b=d[h];q=function(){var v,u,r;r=[];v=0;for(u=a.length;v<u;v++){s=
a[v];s<=h&&r.push(s)}return r}().length;q=h-q;switch(b.o){case "+":[].splice.apply(p,[q,q-1-q+1].concat(b.v));break;case "-":[].splice.apply(p,[q,q-q+1].concat([]));a[a.length]=q;break;case "r":p[q]=b.v;break;case "I":p[q]+=b.v;break;case "L":p[q]=this.apply_list_diff(p[q],b.v);break;case "dL":p[q]=this.apply_list_diff_dmp(p[q],b.v);break;case "O":p[q]=this.apply_object_diff(p[q],b.v);break;case "d":b=this.dmp.diff_fromDelta(p[q],b.v);b=this.dmp.patch_make(p[q],b);b=this.dmp.patch_apply(b,p[q]);p[q]=
b[0]}}return p};k.prototype.apply_list_diff_dmp=function(g,d){var a,b;b=this._serialize_to_text(g);a=this.dmp.diff_fromDelta(b,d);return this._text_to_array(this.dmp.patch_apply(this.dmp.patch_make(b,a),b)[0])};k.prototype.apply_object_diff=function(g,d){var a,b,h;h=this.deepCopy(g);for(a in d)if(c.call(d,a)){b=d[a];if(b.o==="-")delete h[a];else h[a]=this.apply_diff(h[a],b)}return h};k.prototype.apply_object_diff_with_offsets=function(g,d,a,b){var h,j;g=this.deepCopy(g);for(j in d)if(c.call(d,j)){h=
d[j];switch(h.o){case "+":g[j]=h.v;break;case "-":delete g[j];break;case "r":g[j]=h.v;break;case "I":g[j]+=h.v;break;case "L":g[j]=this.apply_list_diff(g[j],h.v);break;case "O":g[j]=this.apply_object_diff(g[j],h.v);break;case "d":h=this.dmp.diff_fromDelta(g[j],h.v);h=this.dmp.patch_make(g[j],h);if(j===a)g[j]=this.patch_apply_with_offsets(h,g[j],b);else{h=this.dmp.patch_apply(h,g[j]);g[j]=h[0]}}}return g};k.prototype.apply_diff=function(g,d){var a;switch(d.o){case "+":return d.v;case "-":return null;
case "r":return d.v;case "I":return g+d.v;case "L":return this.apply_list_diff(g,d.v);case "dL":return this.apply_list_diff_dmp(g,d.v);case "O":return this.apply_object_diff(g,d.v);case "d":a=this.dmp.diff_fromDelta(g,d.v);a=this.dmp.patch_make(g,a);a=this.dmp.patch_apply(a,g);return a[0]}};k.prototype.transform_list_diff=function(g,d,a,b){var h,j,m,p,q,s,w,v,u,r;h={};m=[];j=[];b=b!=null&&"item"in b?b.item:null;for(q in d)if(c.call(d,q)){p=d[q];q=parseInt(q);p.o==="+"&&m.push(q);p.o==="-"&&j.push(q)}w=
s=0;for(q in g)if(c.call(g,q)){p=g[q];q=parseInt(q);u=function(){var x,B,z;z=[];x=0;for(B=m.length;x<B;x++){r=m[x];r<q&&z.push(r)}return z}().length;v=function(){var x,B,z;z=[];x=0;for(B=j.length;x<B;x++){r=j[x];r<q&&z.push(r)}return z}().length;if(s+1===q)q+=w;else q=q+u-v;s=q;w=u-v;v=String(q);h[v]=p;if(v in d)if(!(p.o==="+"&&d[q].o==="+"))if(p.o==="-")d[q].o==="-"&&delete h[v];else if(d[q].o==="-"){if(p.o==="r")h[v]={o:"+",v:p.v};if(p.o===false)h[v]={o:"+",v:this.apply_object_diff(a[v],p.v)}}else{u=
{};u[v]=p;p={};p[v]=d[q];p=this.transform_object_diff(u,p,a,b);h[v]=p[v]}}return h};k.prototype.transform_list_diff_dmp=function(g,d,a){a=this._serialize_to_text(a);g=this.dmp.patch_make(a,this.dmp.diff_fromDelta(a,g));d=this.dmp.patch_apply(this.dmp.patch_make(a,this.dmp.diff_fromDelta(a,d)),a)[0];g=this.dmp.patch_apply(g,d)[0];if(g!==d){d=this.dmp.diff_lineMode_(d,g);d.length>2&&this.dmp.diff_cleanupEfficiency(d);if(d.length>0)return this.dmp.diff_toDelta(d)}return""};k.prototype.transform_object_diff=
function(g,d,a,b){var h,j,m,p;h=this.deepCopy(g);if(b!=null&&"attributes"in b)b=b.attributes;for(m in g)if(c.call(g,m)){j=g[m];if(m in d){if(b!=null&&"attributes"in b){b=b.attributes;b=b!=null&&m in b?b[m]:null}else b=null;g=a[m];d=d[m];if(j.o==="+"&&d.o==="+")if(this.equals(j.v,d.v))delete h[m];else h[m]=this.diff(d.v,j.v,b);else if(j.o==="-"&&d.o==="-")delete h[m];else if(d.o==="-"&&(p=j.o)!=="+"&&p!=="-"){h[m]={o:"+"};h[m].v=this.apply_diff(g,j)}else if(j.o==="O"&&d.o==="O")h[m]={o:"O",v:this.transform_object_diff(j.v,
d.v,g,b)};else if(j.o==="L"&&d.o==="L")h[m]={o:"L",v:this.transform_list_diff(j.v,d.v,g,b)};else if(j.o==="dL"&&d.o==="dL")h[m]={o:"dL",v:this.transform_list_diff_dmp(j.v,d.v,g,b)};else if(j.o==="d"&&d.o==="d"){delete h[m];b=this.dmp.patch_make(g,this.dmp.diff_fromDelta(g,j.v));j=this.dmp.patch_make(g,this.dmp.diff_fromDelta(g,d.v));j=this.dmp.patch_apply(j,g)[0];b=this.dmp.patch_apply(b,j)[0];if(b!==j){b=this.dmp.diff_main(j,b);b.length>2&&this.dmp.diff_cleanupEfficiency(b);if(b.length>0)h[m]={o:"d",
v:this.dmp.diff_toDelta(b)}}}return h}}};k.prototype.patch_apply_with_offsets=function(g,d,a){var b,h,j,m,p,q,s,w,v,u,r,x,B,z,I,J,E;if(g.length===0)return d;g=this.dmp.patch_deepCopy(g);u=this.dmp.patch_addPadding(g);d=u+d+u;this.dmp.patch_splitMax(g);x=B=j=0;for(I=g.length;0<=I?B<I:B>I;x=0<=I?++B:--B){p=g[x].start2+j;s=this.dmp.diff_text1(g[x].diffs);m=-1;if(s.length>this.dmp.Match_MaxBits){r=this.dmp.match_main(d,s.substring(0,this.dmp.Match_MaxBits),p);if(r!==-1){m=this.dmp.match_main(d,s.substring(s.length-
this.dmp.Match_MaxBits),p+s.length-this.dmp.Match_MaxBits);if(m===-1||r>=m)r=-1}}else r=this.dmp.match_main(d,s,p);if(r===-1)j-=g[x].length2-g[x].length1;else{j=r-p;m=m===-1?d.substring(r,r+s.length):d.substring(r,m+this.dmp.Match_MaxBits);m=this.dmp.diff_main(s,m,false);if(!(s.length>this.dmp.Match_MaxBits&&this.dmp.diff_levenshtein(m)/s.length>this.dmp.Patch_DeleteThreshold)){q=p=s=0;for(J=g[x].diffs.length;0<=J?p<J:p>J;q=0<=J?++p:--p){v=g[x].diffs[q];if(v[0]!==0)w=this.dmp.diff_xIndex(m,s);if(v[0]===
1){d=d.substring(0,r+w)+v[1]+d.substring(r+w);q=b=0;for(h=a.length;0<=h?b<h:b>h;q=0<=h?++b:--b)if(a[q]+u.length>r+w)a[q]+=v[1].length}else if(v[0]===-1){h=r+w;b=r+this.dmp.diff_xIndex(m,s+v[1].length);d=d.substring(0,h)+d.substring(b);q=z=0;for(E=a.length;0<=E?z<E:z>E;q=0<=E?++z:--z)if(a[q]+u.length>h)if(a[q]+u.length<b)a[q]=h-u.length;else a[q]-=b-h}if(v[0]!==-1)s+=v[1].length}}}}return d=d.substring(u.length,d.length-u.length)};return k}();window.jsondiff=e}).call(this);function diff_match_patch(){this.Diff_Timeout=1;this.Diff_EditCost=4;this.Match_Threshold=0.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=0.5;this.Patch_Margin=4;this.Match_MaxBits=32}var DIFF_DELETE=-1,DIFF_INSERT=1,DIFF_EQUAL=0;
diff_match_patch.prototype.diff_main=function(e,f,c,k){if(typeof k=="undefined")k=this.Diff_Timeout<=0?Number.MAX_VALUE:(new Date).getTime()+this.Diff_Timeout*1E3;k=k;if(e==null||f==null)throw Error("Null input. (diff_main)");if(e==f){if(e)return[[DIFF_EQUAL,e]];return[]}if(typeof c=="undefined")c=true;var g=c,d=this.diff_commonPrefix(e,f);c=e.substring(0,d);e=e.substring(d);f=f.substring(d);d=this.diff_commonSuffix(e,f);var a=e.substring(e.length-d);e=e.substring(0,e.length-d);f=f.substring(0,f.length-
d);e=this.diff_compute_(e,f,g,k);c&&e.unshift([DIFF_EQUAL,c]);a&&e.push([DIFF_EQUAL,a]);this.diff_cleanupMerge(e);return e};
diff_match_patch.prototype.diff_compute_=function(e,f,c,k){if(!e)return[[DIFF_INSERT,f]];if(!f)return[[DIFF_DELETE,e]];var g=e.length>f.length?e:f,d=e.length>f.length?f:e,a=g.indexOf(d);if(a!=-1){c=[[DIFF_INSERT,g.substring(0,a)],[DIFF_EQUAL,d],[DIFF_INSERT,g.substring(a+d.length)]];if(e.length>f.length)c[0][0]=c[2][0]=DIFF_DELETE;return c}if(d.length==1)return[[DIFF_DELETE,e],[DIFF_INSERT,f]];if(g=this.diff_halfMatch_(e,f)){f=g[1];d=g[3];e=g[4];g=this.diff_main(g[0],g[2],c,k);c=this.diff_main(f,
d,c,k);return g.concat([[DIFF_EQUAL,e]],c)}if(c&&e.length>100&&f.length>100)return this.diff_lineMode_(e,f,k);return this.diff_bisect_(e,f,k)};
diff_match_patch.prototype.diff_lineMode_=function(e,f,c){var k=this.diff_linesToChars_(e,f);e=k.chars1;f=k.chars2;k=k.lineArray;e=this.diff_main(e,f,false,c);this.diff_charsToLines_(e,k);this.diff_cleanupSemantic(e);e.push([DIFF_EQUAL,""]);for(var g=k=f=0,d="",a="";f<e.length;){switch(e[f][0]){case DIFF_INSERT:g++;a+=e[f][1];break;case DIFF_DELETE:k++;d+=e[f][1];break;case DIFF_EQUAL:if(k>=1&&g>=1){e.splice(f-k-g,k+g);f=f-k-g;k=this.diff_main(d,a,false,c);for(g=k.length-1;g>=0;g--)e.splice(f,0,k[g]);
f+=k.length}k=g=0;a=d=""}f++}e.pop();return e};
diff_match_patch.prototype.diff_bisect_=function(e,f,c){for(var k=e.length,g=f.length,d=Math.ceil((k+g)/2),a=2*d,b=Array(a),h=Array(a),j=0;j<a;j++){b[j]=-1;h[j]=-1}b[d+1]=0;h[d+1]=0;j=k-g;for(var m=j%2!=0,p=0,q=0,s=0,w=0,v=0;v<d;v++){if((new Date).getTime()>c)break;for(var u=-v+p;u<=v-q;u+=2){var r=d+u,x;x=u==-v||u!=v&&b[r-1]<b[r+1]?b[r+1]:b[r-1]+1;for(var B=x-u;x<k&&B<g&&e.charAt(x)==f.charAt(B);){x++;B++}b[r]=x;if(x>k)q+=2;else if(B>g)p+=2;else if(m){r=d+j-u;if(r>=0&&r<a&&h[r]!=-1){var z=k-h[r];
if(x>=z)return this.diff_bisectSplit_(e,f,x,B,c)}}}for(u=-v+s;u<=v-w;u+=2){r=d+u;z=u==-v||u!=v&&h[r-1]<h[r+1]?h[r+1]:h[r-1]+1;for(x=z-u;z<k&&x<g&&e.charAt(k-z-1)==f.charAt(g-x-1);){z++;x++}h[r]=z;if(z>k)w+=2;else if(x>g)s+=2;else if(!m){r=d+j-u;if(r>=0&&r<a&&b[r]!=-1){x=b[r];B=d+x-r;z=k-z;if(x>=z)return this.diff_bisectSplit_(e,f,x,B,c)}}}}return[[DIFF_DELETE,e],[DIFF_INSERT,f]]};
diff_match_patch.prototype.diff_bisectSplit_=function(e,f,c,k,g){var d=e.substring(0,c),a=f.substring(0,k);e=e.substring(c);f=f.substring(k);d=this.diff_main(d,a,false,g);g=this.diff_main(e,f,false,g);return d.concat(g)};
diff_match_patch.prototype.diff_linesToChars_=function(e,f){function c(b){for(var h="",j=0,m=-1,p=k.length;m<b.length-1;){m=b.indexOf("\n",j);if(m==-1)m=b.length-1;var q=b.substring(j,m+1);j=m+1;if(g.hasOwnProperty?g.hasOwnProperty(q):g[q]!==undefined)h+=String.fromCharCode(g[q]);else{h+=String.fromCharCode(p);g[q]=p;k[p++]=q}}return h}var k=[],g={};k[0]="";var d=c(e),a=c(f);return{chars1:d,chars2:a,lineArray:k}};
diff_match_patch.prototype.diff_charsToLines_=function(e,f){for(var c=0;c<e.length;c++){for(var k=e[c][1],g=[],d=0;d<k.length;d++)g[d]=f[k.charCodeAt(d)];e[c][1]=g.join("")}};diff_match_patch.prototype.diff_commonPrefix=function(e,f){if(!e||!f||e.charAt(0)!=f.charAt(0))return 0;for(var c=0,k=Math.min(e.length,f.length),g=k,d=0;c<g;){if(e.substring(d,g)==f.substring(d,g))d=c=g;else k=g;g=Math.floor((k-c)/2+c)}return g};
diff_match_patch.prototype.diff_commonSuffix=function(e,f){if(!e||!f||e.charAt(e.length-1)!=f.charAt(f.length-1))return 0;for(var c=0,k=Math.min(e.length,f.length),g=k,d=0;c<g;){if(e.substring(e.length-g,e.length-d)==f.substring(f.length-g,f.length-d))d=c=g;else k=g;g=Math.floor((k-c)/2+c)}return g};
diff_match_patch.prototype.diff_commonOverlap_=function(e,f){var c=e.length,k=f.length;if(c==0||k==0)return 0;if(c>k)e=e.substring(c-k);else if(c<k)f=f.substring(0,c);c=Math.min(c,k);if(e==f)return c;k=0;for(var g=1;;){var d=e.substring(c-g);d=f.indexOf(d);if(d==-1)return k;g+=d;if(d==0||e.substring(c-g)==f.substring(0,g)){k=g;g++}}};
diff_match_patch.prototype.diff_halfMatch_=function(e,f){function c(j,m,p){for(var q=j.substring(p,p+Math.floor(j.length/4)),s=-1,w="",v,u,r,x;(s=m.indexOf(q,s+1))!=-1;){var B=d.diff_commonPrefix(j.substring(p),m.substring(s)),z=d.diff_commonSuffix(j.substring(0,p),m.substring(0,s));if(w.length<z+B){w=m.substring(s-z,s)+m.substring(s,s+B);v=j.substring(0,p-z);u=j.substring(p+B);r=m.substring(0,s-z);x=m.substring(s+B)}}return w.length*2>=j.length?[v,u,r,x,w]:null}if(this.Diff_Timeout<=0)return null;
var k=e.length>f.length?e:f,g=e.length>f.length?f:e;if(k.length<4||g.length*2<k.length)return null;var d=this,a=c(k,g,Math.ceil(k.length/4));k=c(k,g,Math.ceil(k.length/2));if(!a&&!k)return null;else a=k?a?a[4].length>k[4].length?a:k:k:a;var b,h;if(e.length>f.length){k=a[0];g=a[1];b=a[2];h=a[3]}else{b=a[0];h=a[1];k=a[2];g=a[3]}return[k,g,b,h,a[4]]};
diff_match_patch.prototype.diff_cleanupSemantic=function(e){for(var f=false,c=[],k=0,g=null,d=0,a=0,b=0,h=0,j=0;d<e.length;){if(e[d][0]==DIFF_EQUAL){c[k++]=d;a=h;b=j;j=h=0;g=e[d][1]}else{if(e[d][0]==DIFF_INSERT)h+=e[d][1].length;else j+=e[d][1].length;if(g&&g.length<=Math.max(a,b)&&g.length<=Math.max(h,j)){e.splice(c[k-1],0,[DIFF_DELETE,g]);e[c[k-1]+1][0]=DIFF_INSERT;k--;k--;d=k>0?c[k-1]:-1;j=h=b=a=0;g=null;f=true}}d++}f&&this.diff_cleanupMerge(e);this.diff_cleanupSemanticLossless(e);for(d=1;d<e.length;){if(e[d-
1][0]==DIFF_DELETE&&e[d][0]==DIFF_INSERT){f=e[d-1][1];c=e[d][1];k=this.diff_commonOverlap_(f,c);g=this.diff_commonOverlap_(c,f);if(k>=g){if(k>=f.length/2||k>=c.length/2){e.splice(d,0,[DIFF_EQUAL,c.substring(0,k)]);e[d-1][1]=f.substring(0,f.length-k);e[d+1][1]=c.substring(k);d++}}else if(g>=f.length/2||g>=c.length/2){e.splice(d,0,[DIFF_EQUAL,f.substring(0,g)]);e[d-1][0]=DIFF_INSERT;e[d-1][1]=c.substring(0,c.length-g);e[d+1][0]=DIFF_DELETE;e[d+1][1]=f.substring(g);d++}d++}d++}};
diff_match_patch.prototype.diff_cleanupSemanticLossless=function(e){function f(p,q){if(!p||!q)return 6;var s=p.charAt(p.length-1),w=q.charAt(0),v=s.match(diff_match_patch.nonAlphaNumericRegex_),u=w.match(diff_match_patch.nonAlphaNumericRegex_),r=v&&s.match(diff_match_patch.whitespaceRegex_),x=u&&w.match(diff_match_patch.whitespaceRegex_);s=r&&s.match(diff_match_patch.linebreakRegex_);w=x&&w.match(diff_match_patch.linebreakRegex_);var B=s&&p.match(diff_match_patch.blanklineEndRegex_),z=w&&q.match(diff_match_patch.blanklineStartRegex_);
if(B||z)return 5;else if(s||w)return 4;else if(v&&!r&&x)return 3;else if(r||x)return 2;else if(v||u)return 1;return 0}for(var c=1;c<e.length-1;){if(e[c-1][0]==DIFF_EQUAL&&e[c+1][0]==DIFF_EQUAL){var k=e[c-1][1],g=e[c][1],d=e[c+1][1],a=this.diff_commonSuffix(k,g);if(a){var b=g.substring(g.length-a);k=k.substring(0,k.length-a);g=b+g.substring(0,g.length-a);d=b+d}a=k;b=g;for(var h=d,j=f(k,g)+f(g,d);g.charAt(0)===d.charAt(0);){k+=g.charAt(0);g=g.substring(1)+d.charAt(0);d=d.substring(1);var m=f(k,g)+f(g,
d);if(m>=j){j=m;a=k;b=g;h=d}}if(e[c-1][1]!=a){if(a)e[c-1][1]=a;else{e.splice(c-1,1);c--}e[c][1]=b;if(h)e[c+1][1]=h;else{e.splice(c+1,1);c--}}}c++}};diff_match_patch.nonAlphaNumericRegex_=/[^a-zA-Z0-9]/;diff_match_patch.whitespaceRegex_=/\s/;diff_match_patch.linebreakRegex_=/[\r\n]/;diff_match_patch.blanklineEndRegex_=/\n\r?\n$/;diff_match_patch.blanklineStartRegex_=/^\r?\n\r?\n/;
diff_match_patch.prototype.diff_cleanupEfficiency=function(e){for(var f=false,c=[],k=0,g=null,d=0,a=false,b=false,h=false,j=false;d<e.length;){if(e[d][0]==DIFF_EQUAL){if(e[d][1].length<this.Diff_EditCost&&(h||j)){c[k++]=d;a=h;b=j;g=e[d][1]}else{k=0;g=null}h=j=false}else{if(e[d][0]==DIFF_DELETE)j=true;else h=true;if(g&&(a&&b&&h&&j||g.length<this.Diff_EditCost/2&&a+b+h+j==3)){e.splice(c[k-1],0,[DIFF_DELETE,g]);e[c[k-1]+1][0]=DIFF_INSERT;k--;g=null;if(a&&b){h=j=true;k=0}else{k--;d=k>0?c[k-1]:-1;h=j=
false}f=true}}d++}f&&this.diff_cleanupMerge(e)};
diff_match_patch.prototype.diff_cleanupMerge=function(e){e.push([DIFF_EQUAL,""]);for(var f=0,c=0,k=0,g="",d="",a;f<e.length;)switch(e[f][0]){case DIFF_INSERT:k++;d+=e[f][1];f++;break;case DIFF_DELETE:c++;g+=e[f][1];f++;break;case DIFF_EQUAL:if(c+k>1){if(c!==0&&k!==0){a=this.diff_commonPrefix(d,g);if(a!==0){if(f-c-k>0&&e[f-c-k-1][0]==DIFF_EQUAL)e[f-c-k-1][1]+=d.substring(0,a);else{e.splice(0,0,[DIFF_EQUAL,d.substring(0,a)]);f++}d=d.substring(a);g=g.substring(a)}a=this.diff_commonSuffix(d,g);if(a!==
0){e[f][1]=d.substring(d.length-a)+e[f][1];d=d.substring(0,d.length-a);g=g.substring(0,g.length-a)}}if(c===0)e.splice(f-k,c+k,[DIFF_INSERT,d]);else k===0?e.splice(f-c,c+k,[DIFF_DELETE,g]):e.splice(f-c-k,c+k,[DIFF_DELETE,g],[DIFF_INSERT,d]);f=f-c-k+(c?1:0)+(k?1:0)+1}else if(f!==0&&e[f-1][0]==DIFF_EQUAL){e[f-1][1]+=e[f][1];e.splice(f,1)}else f++;c=k=0;d=g=""}e[e.length-1][1]===""&&e.pop();c=false;for(f=1;f<e.length-1;){if(e[f-1][0]==DIFF_EQUAL&&e[f+1][0]==DIFF_EQUAL)if(e[f][1].substring(e[f][1].length-
e[f-1][1].length)==e[f-1][1]){e[f][1]=e[f-1][1]+e[f][1].substring(0,e[f][1].length-e[f-1][1].length);e[f+1][1]=e[f-1][1]+e[f+1][1];e.splice(f-1,1);c=true}else if(e[f][1].substring(0,e[f+1][1].length)==e[f+1][1]){e[f-1][1]+=e[f+1][1];e[f][1]=e[f][1].substring(e[f+1][1].length)+e[f+1][1];e.splice(f+1,1);c=true}f++}c&&this.diff_cleanupMerge(e)};
diff_match_patch.prototype.diff_xIndex=function(e,f){var c=0,k=0,g=0,d=0,a;for(a=0;a<e.length;a++){if(e[a][0]!==DIFF_INSERT)c+=e[a][1].length;if(e[a][0]!==DIFF_DELETE)k+=e[a][1].length;if(c>f)break;g=c;d=k}if(e.length!=a&&e[a][0]===DIFF_DELETE)return d;return d+(f-g)};
diff_match_patch.prototype.diff_prettyHtml=function(e){for(var f=[],c=/&/g,k=/</g,g=/>/g,d=/\n/g,a=0;a<e.length;a++){var b=e[a][0],h=e[a][1].replace(c,"&amp;").replace(k,"&lt;").replace(g,"&gt;").replace(d,"&para;<br>");switch(b){case DIFF_INSERT:f[a]='<ins style="background:#e6ffe6;">'+h+"</ins>";break;case DIFF_DELETE:f[a]='<del style="background:#ffe6e6;">'+h+"</del>";break;case DIFF_EQUAL:f[a]="<span>"+h+"</span>"}}return f.join("")};
diff_match_patch.prototype.diff_text1=function(e){for(var f=[],c=0;c<e.length;c++)if(e[c][0]!==DIFF_INSERT)f[c]=e[c][1];return f.join("")};diff_match_patch.prototype.diff_text2=function(e){for(var f=[],c=0;c<e.length;c++)if(e[c][0]!==DIFF_DELETE)f[c]=e[c][1];return f.join("")};
diff_match_patch.prototype.diff_levenshtein=function(e){for(var f=0,c=0,k=0,g=0;g<e.length;g++){var d=e[g][1];switch(e[g][0]){case DIFF_INSERT:c+=d.length;break;case DIFF_DELETE:k+=d.length;break;case DIFF_EQUAL:f+=Math.max(c,k);k=c=0}}f+=Math.max(c,k);return f};
diff_match_patch.prototype.diff_toDelta=function(e){for(var f=[],c=0;c<e.length;c++)switch(e[c][0]){case DIFF_INSERT:f[c]="+"+encodeURI(e[c][1]);break;case DIFF_DELETE:f[c]="-"+e[c][1].length;break;case DIFF_EQUAL:f[c]="="+e[c][1].length}return f.join("\t").replace(/%20/g," ")};
diff_match_patch.prototype.diff_fromDelta=function(e,f){for(var c=[],k=0,g=0,d=f.split(/\t/g),a=0;a<d.length;a++){var b=d[a].substring(1);switch(d[a].charAt(0)){case "+":try{c[k++]=[DIFF_INSERT,decodeURI(b)]}catch(h){throw Error("Illegal escape in diff_fromDelta: "+b);}break;case "-":case "=":var j=parseInt(b,10);if(isNaN(j)||j<0)throw Error("Invalid number in diff_fromDelta: "+b);b=e.substring(g,g+=j);if(d[a].charAt(0)=="=")c[k++]=[DIFF_EQUAL,b];else c[k++]=[DIFF_DELETE,b];break;default:if(d[a])throw Error("Invalid diff operation in diff_fromDelta: "+
d[a]);}}if(g!=e.length)throw Error("Delta length ("+g+") does not equal source text length ("+e.length+").");return c};diff_match_patch.prototype.match_main=function(e,f,c){if(e==null||f==null||c==null)throw Error("Null input. (match_main)");c=Math.max(0,Math.min(c,e.length));return e==f?0:e.length?e.substring(c,c+f.length)==f?c:this.match_bitap_(e,f,c):-1};
diff_match_patch.prototype.match_bitap_=function(e,f,c){function k(u,r){var x=u/f.length,B=Math.abs(c-r);if(!d.Match_Distance)return B?1:x;return x+B/d.Match_Distance}if(f.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var g=this.match_alphabet_(f),d=this,a=this.Match_Threshold,b=e.indexOf(f,c);if(b!=-1){a=Math.min(k(0,b),a);b=e.lastIndexOf(f,c+f.length);if(b!=-1)a=Math.min(k(0,b),a)}var h=1<<f.length-1;b=-1;for(var j,m,p=f.length+e.length,q,s=0;s<f.length;s++){j=0;for(m=
p;j<m;){if(k(s,c+m)<=a)j=m;else p=m;m=Math.floor((p-j)/2+j)}p=m;j=Math.max(1,c-m+1);var w=Math.min(c+m,e.length)+f.length;m=Array(w+2);m[w+1]=(1<<s)-1;for(w=w;w>=j;w--){var v=g[e.charAt(w-1)];m[w]=s===0?(m[w+1]<<1|1)&v:(m[w+1]<<1|1)&v|(q[w+1]|q[w])<<1|1|q[w+1];if(m[w]&h){v=k(s,w-1);if(v<=a){a=v;b=w-1;if(b>c)j=Math.max(1,2*c-b);else break}}}if(k(s+1,c)>a)break;q=m}return b};
diff_match_patch.prototype.match_alphabet_=function(e){for(var f={},c=0;c<e.length;c++)f[e.charAt(c)]=0;for(c=0;c<e.length;c++)f[e.charAt(c)]|=1<<e.length-c-1;return f};
diff_match_patch.prototype.patch_addContext_=function(e,f){if(f.length!=0){for(var c=f.substring(e.start2,e.start2+e.length1),k=0;f.indexOf(c)!=f.lastIndexOf(c)&&c.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;){k+=this.Patch_Margin;c=f.substring(e.start2-k,e.start2+e.length1+k)}k+=this.Patch_Margin;(c=f.substring(e.start2-k,e.start2))&&e.diffs.unshift([DIFF_EQUAL,c]);(k=f.substring(e.start2+e.length1,e.start2+e.length1+k))&&e.diffs.push([DIFF_EQUAL,k]);e.start1-=c.length;e.start2-=
c.length;e.length1+=c.length+k.length;e.length2+=c.length+k.length}};
diff_match_patch.prototype.patch_make=function(e,f,c){var k;if(typeof e=="string"&&typeof f=="string"&&typeof c=="undefined"){k=e;f=this.diff_main(k,f,true);if(f.length>2){this.diff_cleanupSemantic(f);this.diff_cleanupEfficiency(f)}}else if(e&&typeof e=="object"&&typeof f=="undefined"&&typeof c=="undefined"){f=e;k=this.diff_text1(f)}else if(typeof e=="string"&&f&&typeof f=="object"&&typeof c=="undefined"){k=e;f=f}else if(typeof e=="string"&&typeof f=="string"&&c&&typeof c=="object"){k=e;f=c}else throw Error("Unknown call format to patch_make.");
if(f.length===0)return[];c=[];e=new diff_match_patch.patch_obj;var g=0,d=0,a=0,b=k;k=k;for(var h=0;h<f.length;h++){var j=f[h][0],m=f[h][1];if(!g&&j!==DIFF_EQUAL){e.start1=d;e.start2=a}switch(j){case DIFF_INSERT:e.diffs[g++]=f[h];e.length2+=m.length;k=k.substring(0,a)+m+k.substring(a);break;case DIFF_DELETE:e.length1+=m.length;e.diffs[g++]=f[h];k=k.substring(0,a)+k.substring(a+m.length);break;case DIFF_EQUAL:if(m.length<=2*this.Patch_Margin&&g&&f.length!=h+1){e.diffs[g++]=f[h];e.length1+=m.length;
e.length2+=m.length}else if(m.length>=2*this.Patch_Margin)if(g){this.patch_addContext_(e,b);c.push(e);e=new diff_match_patch.patch_obj;g=0;b=k;d=a}}if(j!==DIFF_INSERT)d+=m.length;if(j!==DIFF_DELETE)a+=m.length}if(g){this.patch_addContext_(e,b);c.push(e)}return c};
diff_match_patch.prototype.patch_deepCopy=function(e){for(var f=[],c=0;c<e.length;c++){var k=e[c],g=new diff_match_patch.patch_obj;g.diffs=[];for(var d=0;d<k.diffs.length;d++)g.diffs[d]=k.diffs[d].slice();g.start1=k.start1;g.start2=k.start2;g.length1=k.length1;g.length2=k.length2;f[c]=g}return f};
diff_match_patch.prototype.patch_apply=function(e,f){if(e.length==0)return[f,[]];e=this.patch_deepCopy(e);var c=this.patch_addPadding(e);f=c+f+c;this.patch_splitMax(e);for(var k=0,g=[],d=0;d<e.length;d++){var a=e[d].start2+k,b=this.diff_text1(e[d].diffs),h,j=-1;if(b.length>this.Match_MaxBits){h=this.match_main(f,b.substring(0,this.Match_MaxBits),a);if(h!=-1){j=this.match_main(f,b.substring(b.length-this.Match_MaxBits),a+b.length-this.Match_MaxBits);if(j==-1||h>=j)h=-1}}else h=this.match_main(f,b,
a);if(h==-1){g[d]=false;k-=e[d].length2-e[d].length1}else{g[d]=true;k=h-a;a=j==-1?f.substring(h,h+b.length):f.substring(h,j+this.Match_MaxBits);if(b==a)f=f.substring(0,h)+this.diff_text2(e[d].diffs)+f.substring(h+b.length);else{a=this.diff_main(b,a,false);if(b.length>this.Match_MaxBits&&this.diff_levenshtein(a)/b.length>this.Patch_DeleteThreshold)g[d]=false;else{this.diff_cleanupSemanticLossless(a);b=0;var m;for(j=0;j<e[d].diffs.length;j++){var p=e[d].diffs[j];if(p[0]!==DIFF_EQUAL)m=this.diff_xIndex(a,
b);if(p[0]===DIFF_INSERT)f=f.substring(0,h+m)+p[1]+f.substring(h+m);else if(p[0]===DIFF_DELETE)f=f.substring(0,h+m)+f.substring(h+this.diff_xIndex(a,b+p[1].length));if(p[0]!==DIFF_DELETE)b+=p[1].length}}}}}f=f.substring(c.length,f.length-c.length);return[f,g]};
diff_match_patch.prototype.patch_addPadding=function(e){for(var f=this.Patch_Margin,c="",k=1;k<=f;k++)c+=String.fromCharCode(k);for(k=0;k<e.length;k++){e[k].start1+=f;e[k].start2+=f}k=e[0];var g=k.diffs;if(g.length==0||g[0][0]!=DIFF_EQUAL){g.unshift([DIFF_EQUAL,c]);k.start1-=f;k.start2-=f;k.length1+=f;k.length2+=f}else if(f>g[0][1].length){var d=f-g[0][1].length;g[0][1]=c.substring(g[0][1].length)+g[0][1];k.start1-=d;k.start2-=d;k.length1+=d;k.length2+=d}k=e[e.length-1];g=k.diffs;if(g.length==0||
g[g.length-1][0]!=DIFF_EQUAL){g.push([DIFF_EQUAL,c]);k.length1+=f;k.length2+=f}else if(f>g[g.length-1][1].length){d=f-g[g.length-1][1].length;g[g.length-1][1]+=c.substring(0,d);k.length1+=d;k.length2+=d}return c};
diff_match_patch.prototype.patch_splitMax=function(e){for(var f=this.Match_MaxBits,c=0;c<e.length;c++)if(!(e[c].length1<=f)){var k=e[c];e.splice(c--,1);for(var g=k.start1,d=k.start2,a="";k.diffs.length!==0;){var b=new diff_match_patch.patch_obj,h=true;b.start1=g-a.length;b.start2=d-a.length;if(a!==""){b.length1=b.length2=a.length;b.diffs.push([DIFF_EQUAL,a])}for(;k.diffs.length!==0&&b.length1<f-this.Patch_Margin;){a=k.diffs[0][0];var j=k.diffs[0][1];if(a===DIFF_INSERT){b.length2+=j.length;d+=j.length;
b.diffs.push(k.diffs.shift());h=false}else if(a===DIFF_DELETE&&b.diffs.length==1&&b.diffs[0][0]==DIFF_EQUAL&&j.length>2*f){b.length1+=j.length;g+=j.length;h=false;b.diffs.push([a,j]);k.diffs.shift()}else{j=j.substring(0,f-b.length1-this.Patch_Margin);b.length1+=j.length;g+=j.length;if(a===DIFF_EQUAL){b.length2+=j.length;d+=j.length}else h=false;b.diffs.push([a,j]);if(j==k.diffs[0][1])k.diffs.shift();else k.diffs[0][1]=k.diffs[0][1].substring(j.length)}}a=this.diff_text2(b.diffs);a=a.substring(a.length-
this.Patch_Margin);j=this.diff_text1(k.diffs).substring(0,this.Patch_Margin);if(j!==""){b.length1+=j.length;b.length2+=j.length;if(b.diffs.length!==0&&b.diffs[b.diffs.length-1][0]===DIFF_EQUAL)b.diffs[b.diffs.length-1][1]+=j;else b.diffs.push([DIFF_EQUAL,j])}h||e.splice(++c,0,b)}}};diff_match_patch.prototype.patch_toText=function(e){for(var f=[],c=0;c<e.length;c++)f[c]=e[c];return f.join("")};
diff_match_patch.prototype.patch_fromText=function(e){var f=[];if(!e)return f;e=e.split("\n");for(var c=0,k=/^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@$/;c<e.length;){var g=e[c].match(k);if(!g)throw Error("Invalid patch string: "+e[c]);var d=new diff_match_patch.patch_obj;f.push(d);d.start1=parseInt(g[1],10);if(g[2]===""){d.start1--;d.length1=1}else if(g[2]=="0")d.length1=0;else{d.start1--;d.length1=parseInt(g[2],10)}d.start2=parseInt(g[3],10);if(g[4]===""){d.start2--;d.length2=1}else if(g[4]=="0")d.length2=
0;else{d.start2--;d.length2=parseInt(g[4],10)}for(c++;c<e.length;){g=e[c].charAt(0);try{var a=decodeURI(e[c].substring(1))}catch(b){throw Error("Illegal escape in patch_fromText: "+a);}if(g=="-")d.diffs.push([DIFF_DELETE,a]);else if(g=="+")d.diffs.push([DIFF_INSERT,a]);else if(g==" ")d.diffs.push([DIFF_EQUAL,a]);else if(g=="@")break;else if(g!=="")throw Error('Invalid patch mode "'+g+'" in: '+a);c++}}return f};
diff_match_patch.patch_obj=function(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0};
diff_match_patch.patch_obj.prototype.toString=function(){for(var e=["@@ -"+(this.length1===0?this.start1+",0":this.length1==1?this.start1+1:this.start1+1+","+this.length1)+" +"+(this.length2===0?this.start2+",0":this.length2==1?this.start2+1:this.start2+1+","+this.length2)+" @@\n"],f,c=0;c<this.diffs.length;c++){switch(this.diffs[c][0]){case DIFF_INSERT:f="+";break;case DIFF_DELETE:f="-";break;case DIFF_EQUAL:f=" "}e[c+1]=f+encodeURI(this.diffs[c][1])+"\n"}return e.join("").replace(/%20/g," ")};
this.diff_match_patch=diff_match_patch;this.DIFF_DELETE=DIFF_DELETE;this.DIFF_INSERT=DIFF_INSERT;this.DIFF_EQUAL=DIFF_EQUAL;var JSON;JSON||(JSON={});
(function(){function e(j,m){var p,q,s,w,v=d,u,r=m[j];r&&typeof r=="object"&&typeof r.toJSON=="function"&&(r=r.toJSON(j));typeof h=="function"&&(r=h.call(m,j,r));switch(typeof r){case "string":return f(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";d+=a;u=[];if(Object.prototype.toString.apply(r)==="[object Array]"){w=r.length;for(p=0;p<w;p+=1)u[p]=e(p,r)||"null";s=u.length===0?"[]":d?"[\n"+d+u.join(",\n"+d)+"\n"+v+"]":
"["+u.join(",")+"]";d=v;return s}if(h&&typeof h=="object"){w=h.length;for(p=0;p<w;p+=1)typeof h[p]=="string"&&(q=h[p],s=e(q,r),s&&u.push(f(q)+(d?": ":":")+s))}else for(q in r)Object.prototype.hasOwnProperty.call(r,q)&&(s=e(q,r),s&&u.push(f(q)+(d?": ":":")+s));s=u.length===0?"{}":d?"{\n"+d+u.join(",\n"+d)+"\n"+v+"}":"{"+u.join(",")+"}";d=v;return s}}function f(j){g.lastIndex=0;return g.test(j)?'"'+j.replace(g,function(m){var p=b[m];return typeof p=="string"?p:"\\u"+("0000"+m.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+j+'"'}function c(j){return j<10?"0"+j:j}typeof Date.prototype.toJSON!="function"&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,a,b={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;typeof JSON.stringify!="function"&&(JSON.stringify=function(j,m,p){var q;a=d="";if(typeof p=="number")for(q=0;q<p;q+=1)a+=" ";else typeof p=="string"&&(a=p);h=m;if(!m||typeof m=="function"||typeof m=="object"&&typeof m.length=="number")return e("",{"":j});throw Error("JSON.stringify");
});typeof JSON.parse!="function"&&(JSON.parse=function(j,m){function p(s,w){var v,u,r=s[w];if(r&&typeof r=="object")for(v in r)Object.prototype.hasOwnProperty.call(r,v)&&(u=p(r,v),u!==undefined?r[v]=u:delete r[v]);return m.call(s,w,r)}var q;j=String(j);k.lastIndex=0;k.test(j)&&(j=j.replace(k,function(s){return"\\u"+("0000"+s.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(j.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){q=eval("("+j+")");return typeof m=="function"?p({"":q},""):q}throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var e=document,f=window,c={},k=function(){};k.prototype.addEventListener=function(i,l){if(!this._listeners)this._listeners={};i in this._listeners||(this._listeners[i]=[]);var o=this._listeners[i];c.arrIndexOf(o,l)===-1&&o.push(l)};k.prototype.removeEventListener=function(i,l){if(this._listeners&&i in this._listeners){var o=this._listeners[i],n=c.arrIndexOf(o,l);if(n!==-1)if(o.length>1)this._listeners[i]=o.slice(0,n).concat(o.slice(n+1));else delete this._listeners[i]}};k.prototype.dispatchEvent=
function(i){var l=i.type,o=Array.prototype.slice.call(arguments,0);this["on"+l]&&this["on"+l].apply(this,o);if(this._listeners&&l in this._listeners)for(var n=0;n<this._listeners[l].length;n++)this._listeners[l][n].apply(this,o)};var g=function(i,l){this.type=i;if(typeof l!=="undefined")for(var o in l)if(l.hasOwnProperty(o))this[o]=l[o]};g.prototype.toString=function(){var i=[],l;for(l in this)if(this.hasOwnProperty(l)){var o=this[l];if(typeof o==="function")o="[function]";i.push(l+"="+o)}return"SimpleEvent("+
i.join(", ")+")"};var d=function(i){this._events=i||[];this._listeners={}};d.prototype.emit=function(i){this._verifyType(i);if(!this._nuked){var l=Array.prototype.slice.call(arguments,1);this["on"+i]&&this["on"+i].apply(this,l);if(i in this._listeners)for(var o=0;o<this._listeners[i].length;o++)this._listeners[i][o].apply(this,l)}};d.prototype.on=function(i,l){this._verifyType(i);if(!this._nuked){i in this._listeners||(this._listeners[i]=[]);this._listeners[i].push(l)}};d.prototype._verifyType=function(i){c.arrIndexOf(this._events,
i)===-1&&c.log("Event "+JSON.stringify(i)+" not listed "+JSON.stringify(this._events)+" in "+this)};d.prototype.nuke=function(){this._nuked=true;for(var i=0;i<this._events.length;i++)delete this[this._events[i]];this._listeners={}};c.random_string=function(i,l){l=l||37;var o,n=[];for(o=0;o<i;o++)n.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*l),1));return n.join("")};c.random_number=function(i){return Math.floor(Math.random()*i)};c.random_number_string=function(i){var l=
(""+(i-1)).length;return(Array(l+1).join("0")+c.random_number(i)).slice(-l)};c.getOrigin=function(i){i+="/";return i.split("/").slice(0,3).join("/")};c.isSameOriginUrl=function(i,l){if(!l)l=f.location.href;return i.split("/").slice(0,3).join("/")===l.split("/").slice(0,3).join("/")};c.getParentDomain=function(i){if(/^[0-9.]*$/.test(i))return i;if(/^\[/.test(i))return i;if(!/[.]/.test(i))return i;return i.split(".").slice(1).join(".")};c.objectExtend=function(i,l){for(var o in l)if(l.hasOwnProperty(o))i[o]=
l[o];return i};c.polluteGlobalNamespace=function(){"_jp"in f||(f._jp={})};c.closeFrame=function(i,l){return"c"+JSON.stringify([i,l])};c.userSetCode=function(i){return i===1E3||i>=3E3&&i<=4999};c.countRTO=function(i){return i>100?3*i:i+200};c.log=function(){f.console&&console.log&&console.log.apply&&console.log.apply(console,arguments)};c.bind=function(i,l){return i.bind?i.bind(l):function(){return i.apply(l,arguments)}};c.flatUrl=function(i){return i.indexOf("?")===-1&&i.indexOf("#")===-1};c.amendUrl=
function(i){var l=e.location;if(!i)throw Error("Wrong url for SockJS");if(!c.flatUrl(i))throw Error("Only basic urls are supported in SockJS");if(i.indexOf("//")===0)i=l.protocol+i;if(i.indexOf("/")===0)i=l.protocol+"//"+l.host+i;return i=i.replace(/[/]+$/,"")};c.arrIndexOf=function(i,l){for(var o=0;o<i.length;o++)if(i[o]===l)return o;return-1};c.arrSkip=function(i,l){var o=c.arrIndexOf(i,l);return o===-1?i.slice():i.slice(0,o).concat(i.slice(o+1))};c.isArray=Array.isArray||function(i){return{}.toString.call(i).indexOf("Array")>=
0};c.delay=function(i,l){if(typeof i==="function"){l=i;i=0}return setTimeout(l,i)};var a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b={"\u0000":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\u0008":"\\b","\t":"\\t","\n":"\\n","\u000b":"\\u000b","\u000c":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010",
"\u0011":"\\u0011","\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b","\u001c":"\\u001c","\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082","\u0083":"\\u0083","\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089",
"\u008a":"\\u008a","\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094","\u0095":"\\u0095","\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d","\u009e":"\\u009e","\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603",
"\u0604":"\\u0604","\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a","\u202b":"\\u202b","\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063","\u2064":"\\u2064","\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a",
"\u206b":"\\u206b","\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4","\ufff5":"\\ufff5","\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd","\ufffe":"\\ufffe","\uffff":"\\uffff"},h=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
j,m=JSON&&JSON.stringify||function(i){a.lastIndex=0;if(a.test(i))i=i.replace(a,function(l){return b[l]});return'"'+i+'"'},p=function(i){var l,o={},n=[];for(l=0;l<65536;l++)n.push(String.fromCharCode(l));i.lastIndex=0;n.join("").replace(i,function(t){o[t]="\\u"+("0000"+t.charCodeAt(0).toString(16)).slice(-4);return""});i.lastIndex=0;return o};c.quote=function(i){i=m(i);h.lastIndex=0;if(!h.test(i))return i;j||(j=p(h));return i.replace(h,function(l){return j[l]})};var q=["websocket","xdr-streaming",
"xhr-streaming","iframe-eventsource","iframe-htmlfile","xdr-polling","xhr-polling","iframe-xhr-polling","jsonp-polling"];c.probeProtocols=function(){for(var i={},l=0;l<q.length;l++){var o=q[l];i[o]=r[o]&&r[o].enabled()}return i};c.detectProtocols=function(i,l,o){var n={},t=[];l||(l=q);for(var y=0;y<l.length;y++){var A=l[y];n[A]=i[A]}var D=function(F){var C=F.shift();if(n[C])t.push(C);else F.length>0&&D(F)};o.websocket!==false&&D(["websocket"]);if(n["xhr-streaming"]&&!o.null_origin)t.push("xhr-streaming");
else n["xdr-streaming"]&&!o.cookie_needed&&!o.null_origin?t.push("xdr-streaming"):D(["iframe-eventsource","iframe-htmlfile"]);if(n["xhr-polling"]&&!o.null_origin)t.push("xhr-polling");else n["xdr-polling"]&&!o.cookie_needed&&!o.null_origin?t.push("xdr-polling"):D(["iframe-xhr-polling","jsonp-polling"]);return t};c.createHook=function(){var i="a"+c.random_string(8);if(!("_sockjs_global"in f)){var l={};f._sockjs_global=function(o){o in l||(l[o]={id:o,del:function(){delete l[o]}});return l[o]}}return f._sockjs_global(i)};
c.attachMessage=function(i){c.attachEvent("message",i)};c.attachEvent=function(i,l){if(typeof f.addEventListener!=="undefined")f.addEventListener(i,l,false);else{e.attachEvent("on"+i,l);f.attachEvent("on"+i,l)}};c.detachMessage=function(i){c.detachEvent("message",i)};c.detachEvent=function(i,l){if(typeof f.addEventListener!=="undefined")f.removeEventListener(i,l,false);else{e.detachEvent("on"+i,l);f.detachEvent("on"+i,l)}};var s={},w=false,v=function(){for(var i in s){s[i]();delete s[i]}};c.attachEvent("unload",
function(){if(!w){w=true;v()}});c.unload_add=function(i){var l=c.random_string(8);s[l]=i;w&&c.delay(v);return l};c.unload_del=function(i){i in s&&delete s[i]};c.createIframe=function(i,l){var o=e.createElement("iframe"),n,t,y=function(){clearTimeout(n);try{o.onload=null}catch(F){}o.onerror=null},A=function(){if(o){y();setTimeout(function(){o&&o.parentNode.removeChild(o);o=null},0);c.unload_del(t)}},D=function(F){if(o){A();l(F)}};o.src=i;o.style.display="none";o.style.position="absolute";o.onerror=
function(){D("onerror")};o.onload=function(){clearTimeout(n);n=setTimeout(function(){D("onload timeout")},2E3)};e.body.appendChild(o);n=setTimeout(function(){D("timeout")},15E3);t=c.unload_add(A);return{post:function(F,C){try{o&&o.contentWindow&&o.contentWindow.postMessage(F,C)}catch(H){}},cleanup:A,loaded:y}};c.createHtmlfile=function(i,l){var o=new ActiveXObject("htmlfile"),n,t,y,A=function(){clearTimeout(n)},D=function(){if(o){A();c.unload_del(t);y.parentNode.removeChild(y);y=o=null;CollectGarbage()}};
o.open();o.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');o.close();o.parentWindow._jp=f._jp;var F=o.createElement("div");o.body.appendChild(F);y=o.createElement("iframe");F.appendChild(y);y.src=i;n=setTimeout(function(){if(o){D();l("timeout")}},15E3);t=c.unload_add(D);return{post:function(C,H){try{y&&y.contentWindow&&y.contentWindow.postMessage(C,H)}catch(N){}},cleanup:D,loaded:A}};var u=function(){};u.prototype=new d(["chunk","finish"]);u.prototype._start=function(i,
l,o,n){var t=this;try{t.xhr=new XMLHttpRequest}catch(y){}if(!t.xhr)try{t.xhr=new f.ActiveXObject("Microsoft.XMLHTTP")}catch(A){}if(f.ActiveXObject||f.XDomainRequest)l+=(l.indexOf("?")===-1?"?":"&")+"t="+ +new Date;t.unload_ref=c.unload_add(function(){t._cleanup(true)});try{t.xhr.open(i,l,true)}catch(D){t.emit("finish",0,"");t._cleanup();return}if(!n||!n.no_credentials)t.xhr.withCredentials="true";if(n&&n.headers)for(var F in n.headers)t.xhr.setRequestHeader(F,n.headers[F]);t.xhr.onreadystatechange=
function(){if(t.xhr){var C=t.xhr;switch(C.readyState){case 3:try{var H=C.status,N=C.responseText}catch(Y){}if(H===1223)H=204;N&&N.length>0&&t.emit("chunk",H,N);break;case 4:H=C.status;if(H===1223)H=204;t.emit("finish",H,C.responseText);t._cleanup(false)}}};t.xhr.send(o)};u.prototype._cleanup=function(i){if(this.xhr){c.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(i)try{this.xhr.abort()}catch(l){}this.unload_ref=this.xhr=null}};u.prototype.close=function(){this.nuke();this._cleanup(true)};
(c.XHRCorsObject=function(){var i=this,l=arguments;c.delay(function(){i._start.apply(i,l)})}).prototype=new u;(c.XHRLocalObject=function(i,l,o){var n=this;c.delay(function(){n._start(i,l,o,{no_credentials:true})})}).prototype=new u;u=c.XDRObject=function(i,l,o){var n=this;c.delay(function(){n._start(i,l,o)})};u.prototype=new d(["chunk","finish"]);u.prototype._start=function(i,l,o){var n=this,t=new XDomainRequest;l+=(l.indexOf("?")===-1?"?":"&")+"t="+ +new Date;var y=t.ontimeout=t.onerror=function(){n.emit("finish",
0,"");n._cleanup(false)};t.onprogress=function(){n.emit("chunk",200,t.responseText)};t.onload=function(){n.emit("finish",200,t.responseText);n._cleanup(false)};n.xdr=t;n.unload_ref=c.unload_add(function(){n._cleanup(true)});try{n.xdr.open(i,l);n.xdr.send(o)}catch(A){y()}};u.prototype._cleanup=function(i){if(this.xdr){c.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(i)try{this.xdr.abort()}catch(l){}this.unload_ref=this.xdr=null}};u.prototype.close=
function(){this.nuke();this._cleanup(true)};c.isXHRCorsCapable=function(){if(f.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest)return 1;if(f.XDomainRequest&&e.domain)return 2;if(G.enabled())return 3;return 4};var r=function(i,l,o){if(this===f)return new r(i,l,o);var n=this,t;n._options={devel:false,debug:false,protocols_whitelist:[],info:undefined,rtt:undefined};o&&c.objectExtend(n._options,o);n._base_url=c.amendUrl(i);n._server=n._options.server||c.random_number_string(1E3);if(n._options.protocols_whitelist&&
n._options.protocols_whitelist.length)t=n._options.protocols_whitelist;else(t=typeof l==="string"&&l.length>0?[l]:c.isArray(l)?l:null)&&n._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.');n._protocols=[];n.protocol=null;n.readyState=r.CONNECTING;n._ir=X(n._base_url);n._ir.onfinish=function(y,A){n._ir=null;if(y){if(n._options.info)y=c.objectExtend(y,n._options.info);if(n._options.rtt)A=n._options.rtt;n._applyInfo(y,
A,t);n._didClose()}else n._didClose(1002,"Can't connect to server",true)}};r.prototype=new k;r.version="0.3.4";r.CONNECTING=0;r.OPEN=1;r.CLOSING=2;r.CLOSED=3;r.prototype._debug=function(){this._options.debug&&c.log.apply(c,arguments)};r.prototype._dispatchOpen=function(){if(this.readyState===r.CONNECTING){if(this._transport_tref){clearTimeout(this._transport_tref);this._transport_tref=null}this.readyState=r.OPEN;this.dispatchEvent(new g("open"))}else this._didClose(1006,"Server lost session")};r.prototype._dispatchMessage=
function(i){this.readyState===r.OPEN&&this.dispatchEvent(new g("message",{data:i}))};r.prototype._dispatchHeartbeat=function(){this.readyState===r.OPEN&&this.dispatchEvent(new g("heartbeat",{}))};r.prototype._didClose=function(i,l,o){var n=this;if(n.readyState!==r.CONNECTING&&n.readyState!==r.OPEN&&n.readyState!==r.CLOSING)throw Error("INVALID_STATE_ERR");if(n._ir){n._ir.nuke();n._ir=null}if(n._transport){n._transport.doCleanup();n._transport=null}var t=new g("close",{code:i,reason:l,wasClean:c.userSetCode(i)});
if(!c.userSetCode(i)&&n.readyState===r.CONNECTING&&!o){if(n._try_next_protocol(t))return;t=new g("close",{code:2E3,reason:"All transports failed",wasClean:false,last_event:t})}n.readyState=r.CLOSED;c.delay(function(){n.dispatchEvent(t)})};r.prototype._didMessage=function(i){switch(i.slice(0,1)){case "o":this._dispatchOpen();break;case "a":i=JSON.parse(i.slice(1)||"[]");for(var l=0;l<i.length;l++)this._dispatchMessage(i[l]);break;case "m":i=JSON.parse(i.slice(1)||"null");this._dispatchMessage(i);break;
case "c":i=JSON.parse(i.slice(1)||"[]");this._didClose(i[0],i[1]);break;case "h":this._dispatchHeartbeat()}};r.prototype._try_next_protocol=function(i){var l=this;if(l.protocol){l._debug("Closed transport:",l.protocol,""+i);l.protocol=null}if(l._transport_tref){clearTimeout(l._transport_tref);l._transport_tref=null}for(;;){i=l.protocol=l._protocols.shift();if(!i)return false;if(r[i]&&r[i].need_body===true&&(!e.body||typeof e.readyState!=="undefined"&&e.readyState!=="complete")){l._protocols.unshift(i);
l.protocol="waiting-for-load";c.attachEvent("load",function(){l._try_next_protocol()});return true}if(!r[i]||!r[i].enabled(l._options))l._debug("Skipping transport:",i);else{l._transport_tref=c.delay((l._options.rto||0)*(r[i].roundTrips||1)||5E3,function(){l.readyState===r.CONNECTING&&l._didClose(2007,"Transport timeouted")});var o=c.random_string(8);o=l._base_url+"/"+l._server+"/"+o;l._debug("Opening transport:",i," url:"+o," RTO:"+l._options.rto);l._transport=new r[i](l,o,l._base_url);return true}}};
r.prototype.close=function(i,l){if(i&&!c.userSetCode(i))throw Error("INVALID_ACCESS_ERR");if(this.readyState!==r.CONNECTING&&this.readyState!==r.OPEN)return false;this.readyState=r.CLOSING;this._didClose(i||1E3,l||"Normal closure");return true};r.prototype.send=function(i){if(this.readyState===r.CONNECTING)throw Error("INVALID_STATE_ERR");this.readyState===r.OPEN&&this._transport.doSend(c.quote(""+i));return true};r.prototype._applyInfo=function(i,l,o){this._options.info=i;this._options.rtt=l;this._options.rto=
c.countRTO(l);this._options.info.null_origin=!e.domain;l=c.probeProtocols();this._protocols=c.detectProtocols(l,o,i)};u=r.websocket=function(i,l){var o=this,n=l+"/websocket";n=n.slice(0,5)==="https"?"wss"+n.slice(5):"ws"+n.slice(4);o.ri=i;o.url=n;o.ws=new (f.WebSocket||f.MozWebSocket)(o.url);o.ws.onmessage=function(t){o.ri._didMessage(t.data)};o.unload_ref=c.unload_add(function(){o.ws.close()});o.ws.onclose=function(){o.ri._didMessage(c.closeFrame(1006,"WebSocket connection broken"))}};u.prototype.doSend=
function(i){this.ws.send("["+i+"]")};u.prototype.doCleanup=function(){var i=this.ws;if(i){i.onmessage=i.onclose=null;i.close();c.unload_del(this.unload_ref);this.unload_ref=this.ri=this.ws=null}};u.enabled=function(){return!!(f.WebSocket||f.MozWebSocket)};u.roundTrips=2;var x=function(){};x.prototype.send_constructor=function(i){this.send_buffer=[];this.sender=i};x.prototype.doSend=function(i){this.send_buffer.push(i);this.send_stop||this.send_schedule()};x.prototype.send_schedule_wait=function(){var i=
this,l;i.send_stop=function(){i.send_stop=null;clearTimeout(l)};l=c.delay(25,function(){i.send_stop=null;i.send_schedule()})};x.prototype.send_schedule=function(){var i=this;if(i.send_buffer.length>0){var l="["+i.send_buffer.join(",")+"]";i.send_stop=i.sender(i.trans_url,l,function(o,n){i.send_stop=null;o===false?i.ri._didClose(1006,"Sending error "+n):i.send_schedule_wait()});i.send_buffer=[]}};x.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var B=
function(i,l,o){if(!("_send_form"in this)){var n=this._send_form=e.createElement("form"),t=this._send_area=e.createElement("textarea");t.name="d";n.style.display="none";n.style.position="absolute";n.method="POST";n.enctype="application/x-www-form-urlencoded";n.acceptCharset="UTF-8";n.appendChild(t);e.body.appendChild(n)}n=this._send_form;t=this._send_area;var y="a"+c.random_string(8);n.target=y;n.action=i+"/jsonp_send?i="+y;var A;try{A=e.createElement('<iframe name="'+y+'">')}catch(D){A=e.createElement("iframe");
A.name=y}A.id=y;n.appendChild(A);A.style.display="none";try{t.value=l}catch(F){c.log("Your browser is seriously broken. Go home! "+F.message)}n.submit();var C=function(){if(A.onerror){A.onreadystatechange=A.onerror=A.onload=null;c.delay(500,function(){A.parentNode.removeChild(A);A=null});t.value="";o(true)}};A.onerror=A.onload=C;A.onreadystatechange=function(){A.readyState=="complete"&&C()};return C},z=function(i){return function(l,o,n){(new i("POST",l+"/xhr_send",o)).onfinish=function(t){n(t===200||
t===204,"http status "+t)};return function(t){n(false,t)}}},I=function(i,l){var o,n=e.createElement("script"),t,y=function(H){if(t){t.parentNode.removeChild(t);t=null}if(n){clearTimeout(o);n.parentNode.removeChild(n);n=n.onreadystatechange=n.onerror=n.onload=n.onclick=null;l(H);l=null}},A=false,D=null;n.id="a"+c.random_string(8);n.src=i;n.type="text/javascript";n.charset="UTF-8";n.onerror=function(){D||(D=setTimeout(function(){A||y(c.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};
n.onload=function(){y(c.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};n.onreadystatechange=function(){if(/loaded|closed/.test(n.readyState)){if(n&&n.htmlFor&&n.onclick){A=true;try{n.onclick()}catch(H){}}n&&y(c.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if(typeof n.async==="undefined"&&e.attachEvent)if(/opera/i.test(navigator.userAgent)){t=e.createElement("script");t.text="try{var a = document.getElementById('"+n.id+"'); if(a)a.onerror();}catch(x){};";
n.async=t.async=false}else{try{n.htmlFor=n.id;n.event="onclick"}catch(F){}n.async=true}if(typeof n.async!=="undefined")n.async=true;o=setTimeout(function(){y(c.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);var C=e.getElementsByTagName("head")[0];C.insertBefore(n,C.firstChild);t&&C.insertBefore(t,C.firstChild);return y};u=r["jsonp-polling"]=function(i,l){c.polluteGlobalNamespace();this.ri=i;this.trans_url=l;this.send_constructor(B);this._schedule_recv()};u.prototype=new x;u.prototype._schedule_recv=
function(){var i=this;i._recv_stop=J(i.trans_url+"/jsonp",I,function(l){i._recv_stop=null;if(l)i._is_closing||i.ri._didMessage(l);i._is_closing||i._schedule_recv()})};u.enabled=function(){return true};u.need_body=true;u.prototype.doCleanup=function(){this._is_closing=true;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};var J=function(i,l,o){var n="a"+c.random_string(6);i=i+"?c="+escape("_jp."+n);var t=0;l=l(i,function(y){switch(t){case 0:delete f._jp[n];o(y);
break;case 1:o(y);t=2;break;case 2:delete f._jp[n]}});f._jp[n]=l;return function(){if(f._jp[n]){t=1;f._jp[n](c.closeFrame(1E3,"JSONP user aborted read"))}}};u=function(){};u.prototype=new x;u.prototype.run=function(i,l,o,n,t){this.ri=i;this.trans_url=l;this.send_constructor(z(t));this.poll=new P(i,n,l+o,t)};u.prototype.doCleanup=function(){if(this.poll){this.poll.abort();this.poll=null}};var E=r["xhr-streaming"]=function(i,l){this.run(i,l,"/xhr_streaming",L,c.XHRCorsObject)};E.prototype=new u;E.enabled=
function(){return f.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&!/opera/i.test(navigator.userAgent)};E.roundTrips=2;E.need_body=true;x=r["xdr-streaming"]=function(i,l){this.run(i,l,"/xhr_streaming",L,c.XDRObject)};x.prototype=new u;x.enabled=function(){return!!f.XDomainRequest};x.roundTrips=2;var Q=r["xhr-polling"]=function(i,l){this.run(i,l,"/xhr",L,c.XHRCorsObject)};Q.prototype=new u;Q.enabled=E.enabled;Q.roundTrips=2;E=r["xdr-polling"]=function(i,l){this.run(i,l,"/xhr",L,c.XDRObject)};
E.prototype=new u;E.enabled=x.enabled;E.roundTrips=2;var G=function(){};G.prototype.i_constructor=function(i,l,o){var n=this;n.ri=i;n.origin=c.getOrigin(o);n.base_url=o;n.trans_url=l;i=o+"/iframe.html";if(n.ri._options.devel)i+="?t="+ +new Date;n.window_id=c.random_string(8);i+="#"+n.window_id;n.iframeObj=c.createIframe(i,function(t){n.ri._didClose(1006,"Unable to load an iframe ("+t+")")});n.onmessage_cb=c.bind(n.onmessage,n);c.attachMessage(n.onmessage_cb)};G.prototype.doCleanup=function(){if(this.iframeObj){c.detachMessage(this.onmessage_cb);
try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(i){}this.iframeObj.cleanup();this.onmessage_cb=this.iframeObj=this.iframeObj=null}};G.prototype.onmessage=function(i){if(i.origin===this.origin){var l=i.data.slice(0,8),o=i.data.slice(8,9);i=i.data.slice(9);if(l===this.window_id)switch(o){case "s":this.iframeObj.loaded();this.postMessage("s",JSON.stringify([r.version,this.protocol,this.trans_url,this.base_url]));break;case "t":this.ri._didMessage(i)}}};G.prototype.postMessage=function(i,
l){this.iframeObj.post(this.window_id+i+(l||""),this.origin)};G.prototype.doSend=function(i){this.postMessage("m",i)};G.enabled=function(){var i=navigator&&navigator.userAgent&&navigator.userAgent.indexOf("Konqueror")!==-1;return(typeof f.postMessage==="function"||typeof f.postMessage==="object")&&!i};var R,S=function(i,l){parent!==f?parent.postMessage(R+i+(l||""),"*"):c.log("Can't postMessage, no parent window.",i,l)},K=function(){};K.prototype._didClose=function(i,l){S("t",c.closeFrame(i,l))};K.prototype._didMessage=
function(i){S("t",i)};K.prototype._doSend=function(i){this._transport.doSend(i)};K.prototype._doCleanup=function(){this._transport.doCleanup()};c.parent_origin=undefined;r.bootstrap_iframe=function(){var i;R=e.location.hash.slice(1);c.attachMessage(function(l){if(l.source===parent){if(typeof c.parent_origin==="undefined")c.parent_origin=l.origin;if(l.origin===c.parent_origin){var o=l.data.slice(0,8),n=l.data.slice(8,9);l=l.data.slice(9);if(o===R)switch(n){case "s":var t=JSON.parse(l);o=t[0];n=t[1];
l=t[2];t=t[3];o!==r.version&&c.log('Incompatibile SockJS! Main site uses: "'+o+'", the iframe: "'+r.version+'".');if(!c.flatUrl(l)||!c.flatUrl(t)){c.log("Only basic urls are supported in SockJS");break}if(!c.isSameOriginUrl(l)||!c.isSameOriginUrl(t)){c.log("Can't connect to different domain from within an iframe. ("+JSON.stringify([f.location.href,l,t])+")");break}i=new K;i._transport=new K[n](i,l,t);break;case "m":i._doSend(l);break;case "c":i&&i._doCleanup();i=null}}}});S("s")};var M=function(i,
l){var o=this;c.delay(function(){o.doXhr(i,l)})};M.prototype=new d(["finish"]);M.prototype.doXhr=function(i,l){var o=this,n=(new Date).getTime(),t=new l("GET",i+"/info"),y=c.delay(8E3,function(){t.ontimeout()});t.onfinish=function(A,D){clearTimeout(y);y=null;if(A===200){var F=(new Date).getTime()-n,C=JSON.parse(D);if(typeof C!=="object")C={};o.emit("finish",C,F)}else o.emit("finish")};t.ontimeout=function(){t.close();o.emit("finish")}};var V=function(i){var l=this,o=function(){var n=new G;n.protocol=
"w-iframe-info-receiver";var t=function(y){if(typeof y==="string"&&y.substr(0,1)==="m"){y=JSON.parse(y.substr(1));l.emit("finish",y[0],y[1])}else l.emit("finish");n.doCleanup();n=null};n.i_constructor({_options:{},_didClose:t,_didMessage:t},i,i)};e.body?o():c.attachEvent("load",o)};V.prototype=new d(["finish"]);var W=function(){var i=this;c.delay(function(){i.emit("finish",{},2E3)})};W.prototype=new d(["finish"]);var X=function(i){if(c.isSameOriginUrl(i))return new M(i,c.XHRLocalObject);switch(c.isXHRCorsCapable()){case 1:return new M(i,
c.XHRLocalObject);case 2:return new M(i,c.XDRObject);case 3:return new V(i);default:return new W}};(K["w-iframe-info-receiver"]=function(i,l,o){(new M(o,c.XHRLocalObject)).onfinish=function(n,t){i._didMessage("m"+JSON.stringify([n,t]));i._didClose()}}).prototype.doCleanup=function(){};d=r["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};d.prototype=new G;d.enabled=function(){return"EventSource"in f&&G.enabled()};d.need_body=true;d.roundTrips=
3;(K["w-iframe-eventsource"]=function(i,l){this.run(i,l,"/eventsource",T,c.XHRLocalObject)}).prototype=new u;d=r["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};d.prototype=new G;d.enabled=function(){return f.XMLHttpRequest&&G.enabled()};d.need_body=true;d.roundTrips=3;(K["w-iframe-xhr-polling"]=function(i,l){this.run(i,l,"/xhr",L,c.XHRLocalObject)}).prototype=new u;d=r["iframe-htmlfile"]=function(){this.protocol="w-iframe-htmlfile";
this.i_constructor.apply(this,arguments)};d.prototype=new G;d.enabled=function(){return G.enabled()};d.need_body=true;d.roundTrips=3;(K["w-iframe-htmlfile"]=function(i,l){this.run(i,l,"/htmlfile",U,c.XHRLocalObject)}).prototype=new u;var P=function(i,l,o,n){this.ri=i;this.Receiver=l;this.recv_url=o;this.AjaxObject=n;this._scheduleRecv()};P.prototype._scheduleRecv=function(){var i=this,l=i.poll=new i.Receiver(i.recv_url,i.AjaxObject),o=0;l.onmessage=function(n){o+=1;i.ri._didMessage(n.data)};l.onclose=
function(n){i.poll=l=l.onmessage=l.onclose=null;i.poll_is_closing||(n.reason==="permanent"?i.ri._didClose(1006,"Polling error ("+n.reason+")"):i._scheduleRecv())}};P.prototype.abort=function(){this.poll_is_closing=true;this.poll&&this.poll.abort()};var T=function(i){var l=this,o=new EventSource(i);o.onmessage=function(n){l.dispatchEvent(new g("message",{data:unescape(n.data)}))};l.es_close=o.onerror=function(n,t){var y=t?"user":o.readyState!==2?"network":"permanent";l.es_close=o.onmessage=o.onerror=
null;o.close();o=null;c.delay(200,function(){l.dispatchEvent(new g("close",{reason:y}))})}};T.prototype=new k;T.prototype.abort=function(){this.es_close&&this.es_close({},true)};var O,U=function(i){var l=this;c.polluteGlobalNamespace();l.id="a"+c.random_string(6,26);i+=(i.indexOf("?")===-1?"?":"&")+"c="+escape("_jp."+l.id);if(O===undefined)if("ActiveXObject"in f)try{O=!!new ActiveXObject("htmlfile")}catch(o){}else O=false;var n=O?c.createHtmlfile:c.createIframe,t;f._jp[l.id]={start:function(){t.loaded()},
message:function(y){l.dispatchEvent(new g("message",{data:y}))},stop:function(){l.iframe_close({},"network")}};l.iframe_close=function(y,A){t.cleanup();l.iframe_close=t=null;delete f._jp[l.id];l.dispatchEvent(new g("close",{reason:A}))};t=n(i,function(){l.iframe_close({},"permanent")})};U.prototype=new k;U.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var L=function(i,l){var o=this,n=0;o.xo=new l("POST",i,null);o.xo.onchunk=function(t,y){if(t===200)for(;;){var A=y.slice(n),
D=A.indexOf("\n");if(D===-1)break;n+=D+1;A=A.slice(0,D);o.dispatchEvent(new g("message",{data:A}))}};o.xo.onfinish=function(t,y){o.xo.onchunk(t,y);o.xo=null;o.dispatchEvent(new g("close",{reason:t===200?"network":"permanent"}))}};L.prototype=new k;L.prototype.abort=function(){if(this.xo){this.xo.close();this.dispatchEvent(new g("close",{reason:"user"}));this.xo=null}};r.getUtils=function(){return c};r.getIframeTransport=function(){return G};return r}();
"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);typeof define==="function"&&define.amd&&define("sockjs",[],function(){return SockJS});(function(){var e,f,c=function(d,a){return function(){return d.apply(a,arguments)}},k={}.hasOwnProperty,g=[].indexOf||function(d){for(var a=0,b=this.length;a<b;a++)if(a in this&&this[a]===d)return a;return-1};e=function(){function d(a,b,h){this.s=a;this.name=b;this._check_pending=c(this._check_pending,this);this.pending=c(this.pending,this);this.on_changes=c(this.on_changes,this);this.retrieve_changes=c(this.retrieve_changes,this);this._send_changes=c(this._send_changes,this);this._queue_change=c(this._queue_change,
this);this._make_change=c(this._make_change,this);this.update=c(this.update,this);this._check_update=c(this._check_update,this);this._notify_client=c(this._notify_client,this);this._index_loaded=c(this._index_loaded,this);this.on_entity_version=c(this.on_entity_version,this);this.get_version=c(this.get_version,this);this.load_versions=c(this.load_versions,this);this.on_index_error=c(this.on_index_error,this);this.on_index_page=c(this.on_index_page,this);this._refresh_store=c(this._refresh_store,this);
this.send=c(this.send,this);this.on_data=c(this.on_data,this);this.start=c(this.start,this);this._remove_entity=c(this._remove_entity,this);this._save_entity=c(this._save_entity,this);this._load_data=c(this._load_data,this);this._verify=c(this._verify,this);this._load_meta=c(this._load_meta,this);this.show_data=c(this.show_data,this);this.on=c(this.on,this);this.jd=this.s.jd;this.options=this.jd.deepCopy(this.s.options);for(b in h)if(k.call(h,b)){a=h[b];this.options[b]=a}this.chan=this.options.n;
this.space=""+this.options.app_id+"/"+this.name;this.username=this.options.username;this.namespace=""+this.username+":"+this.space;this.clientid=null;try{this.clientid=localStorage.getItem(""+this.namespace+"/clientid")}catch(j){this.clientid=null}if(this.clientid==null||this.clientid.indexOf("sjs")!==0){this.clientid="sjs-"+this.s.bversion+"-"+this.uuid(5);try{localStorage.setItem(""+this.namespace+"/clientid")}catch(m){console.log(""+this.name+": couldnt set clientid")}}this.cb_events=["notify",
"notify_init","notify_version","local","get","ready","notify_pending","error"];this.cbs={};this.cb_e=this.cb_l=this.cb_ni=this.cb_np=null;this.cb_n=this.cb_nv=this.cb_r=function(){};this.authorized=this.initialized=false;this.data={last_cv:0,ccid:this.uuid(),store:{},send_queue:[],send_queue_timer:null};this.started=false;if("nostore"in this.options){console.log(""+this.name+": not loading from localstorage");this.loaded=0}else{this._load_meta();this.loaded=this._load_data();console.log(""+this.name+
": localstorage loaded "+this.loaded+" entities")}this._last_pending=null;this._send_backoff=15E3;this._backoff_max=12E4;this._backoff_min=15E3;console.log(""+this.namespace+": bucket created: opts: "+JSON.stringify(this.options))}d.prototype.S4=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};d.prototype.uuid=function(a){var b;a=a||8;for(b=this.S4();a-=1;)b+=this.S4();return b};d.prototype.now=function(){return(new Date).getTime()};d.prototype.on=function(a,b){if(g.call(this.cb_events,
a)>=0){this.cbs[a]=b;switch(a){case "get":case "local":return this.cb_l=b;case "notify":return this.cb_n=b;case "notify_version":return this.cb_nv=b;case "notify_pending":return this.cb_np=b;case "notify_init":return this.cb_ni=b;case "ready":return this.cb_r=b;case "error":return this.cb_e=b}}else throw Error("unsupported callback event");};d.prototype.show_data=function(){var a,b,h;if(this.s.supports_html5_storage()){h=0;for(b in localStorage)if(k.call(localStorage,b)){a=localStorage[b];console.log("["+
b+"]: "+a);h+=1}return console.log(""+h+" total")}};d.prototype._save_meta=function(){if(!this.s.supports_html5_storage())return false;console.log(""+this.name+": save_meta ccid:"+this.data.ccid+" cv:"+this.data.last_cv);try{localStorage.setItem(""+this.namespace+"/ccid",this.data.ccid);localStorage.setItem(""+this.namespace+"/last_cv",this.data.last_cv)}catch(a){return false}return true};d.prototype._load_meta=function(){var a;if(this.s.supports_html5_storage()){this.data.ccid=localStorage.getItem(""+
this.namespace+"/ccid");if((a=this.data).ccid==null)a.ccid=1;this.data.last_cv=localStorage.getItem(""+this.namespace+"/last_cv");if((a=this.data).last_cv==null)a.last_cv=0;return console.log(""+this.name+": load_meta ccid:"+this.data.ccid+" cv:"+this.data.last_cv)}};d.prototype._verify=function(a){if(!("object"in a)||!("version"in a))return false;if(this.jd.entries(a.object)===0)return"last"in a&&this.jd.entries(a.last)>0?true:false;else if(a.version==null)return false;return true};d.prototype._load_data=
function(){var a,b,h,j,m,p,q,s;if(this.s.supports_html5_storage()){p=""+this.namespace+"/e/";m=p.length;j=0;if(localStorage.length===0)return 0;b=q=0;for(s=localStorage.length-1;0<=s?q<=s:q>=s;b=0<=s?++q:--q){h=localStorage.key(b);if(h!=null&&h.substr(0,m)===p){b=h.substr(m,h.length-m);try{a=JSON.parse(localStorage.getItem(h))}catch(w){a=null}if(a!=null)if(this._verify(a)){a.check=null;this.data.store[b]=a;j+=1}else{console.log("ignoring CORRUPT data: "+JSON.stringify(a));this._remove_entity(b)}}}return j}};
d.prototype._save_entity=function(a){var b,h;if(!this.s.supports_html5_storage())return false;h=""+this.namespace+"/e/"+a;a=this.data.store[a];b=JSON.stringify(a);try{localStorage.setItem(h,b)}catch(j){return false}h=JSON.parse(localStorage.getItem(h));return this.jd.equals(a,h)?true:false};d.prototype._remove_entity=function(a){if(!this.s.supports_html5_storage())return false;a=""+this.namespace+"/e/"+a;try{localStorage.removeItem(a)}catch(b){return false}return true};d.prototype.start=function(){var a,
b;console.log(""+this.space+": started initialized: "+this.initialized+" authorized: "+this.authorized);this.namespace=""+this.username+":"+this.space;this.started=true;this.first=false;if(this.authorized)if(this.initialized){console.log(""+this.name+": retrieve changes from start");return this.retrieve_changes()}else{if(!this.first){this.notify_index={};return this._refresh_store()}}else if(this.s.connected){this.first=true;a="limit"in this.options?"i:1:::"+this.options.limit:"i:1:::40";this.irequest_time=
this.now();this.index_request=true;this.notify_index={};b={app_id:this.options.app_id,token:this.options.token,name:this.name,clientid:this.clientid,build:this.s.bversion};if(!this.initialized)b.cmd=a;this.send("init:"+JSON.stringify(b));console.log(""+this.name+": sent init "+JSON.stringify(b)+" waiting for auth")}else console.log(""+this.name+": waiting for connect")};d.prototype.on_data=function(a){var b,h,j;if(a.substr(0,5)==="auth:"){b=a.substr(5);if(b==="expired"){console.log("auth expired");
this.started=false;this.cb_e!=null&&this.cb_e("auth")}else{this.username=b;this.authorized=true;if(this.initialized)return this.start()}}else if(a.substr(0,4)==="cv:?"){console.log(""+this.name+": cv out of sync, refreshing index");return setTimeout(function(m){return function(){return m._refresh_store()}}(this))}else if(a.substr(0,2)==="c:"){b=JSON.parse(a.substr(2));if(this.data.last_cv==="0"&&b.length===0&&!this.cv_check){this.cv_check=true;this._refresh_store()}return this.on_changes(b)}else if(a.substr(0,
2)==="i:"){console.log(""+this.name+":  index msg received: "+(this.now()-this.irequest_time));return this.on_index_page(JSON.parse(a.substr(2)))}else if(a.substr(0,2)==="e:"){j=a.indexOf("\n");h=a.substr(2,j-2);b=h.substr(h.lastIndexOf(".")+1);h=h.substr(0,h.lastIndexOf("."));a=a.substr(j+1);if(a==="?")return this.on_entity_version(null,h,b);else{a=JSON.parse(a);return this.on_entity_version(a.data,h,b)}}else return console.log("unknown message: "+a)};d.prototype.send=function(a){console.log("sending: "+
this.chan+":"+a);return this.s.send(""+this.chan+":"+a)};d.prototype._refresh_store=function(){console.log(""+this.name+": _refresh_store(): loading index");this.send("limit"in this.options?"i:1:::"+this.options.limit:"i:1:::40");this.irequest_time=this.now();this.index_request=true};d.prototype.on_index_page=function(a){var b,h,j,m,p,q,s;j=this.now();console.log(""+this.name+": index response time: "+(j-this.irequest_time));console.log(""+this.name+": on_index_page(): index page received, current= "+
a.current);console.log(a);h=0;s=a.index;p=0;for(q=s.length;p<q;p++){b=s[p];this.notify_index[b.id]=false;h++;setTimeout(function(w){return function(v){return function(){return w.on_entity_version(v.d,v.id,v.v)}}}(this)(b))}if(!("mark"in a)||"limit"in this.options){this.index_request=false;if("current"in a){this.data.last_cv=a.current;this._save_meta()}else this.data.last_cv=0;if(h===0)return this._index_loaded()}else{this.index_request=true;console.log(""+this.name+": index last process time: "+(this.now()-
j)+", page_delay: "+this.options.page_delay);a=a.mark;m=function(w){return function(v){w.send("i:1:"+v+"::100");return w.irequest_time=w.now()}}(this);return setTimeout(function(){return function(w){return function(){return m(w)}}}(this)(a),this.options.page_delay)}};d.prototype.on_index_error=function(){return console.log(""+this.name+": index doesnt exist or other error")};d.prototype.load_versions=function(a,b){var h,j,m,p,q;if(!(a in this.data.store))return false;h=Math.max(this.data.store[a].version-
(b+1),1);q=[];j=m=h;for(p=this.data.store[a].version-1;h<=p?m<=p:m>=p;j=h<=p?++m:--m){console.log(""+this.name+": loading version "+a+"."+j);q.push(this.send("e:"+a+"."+j))}return q};d.prototype.get_version=function(a,b){return this.send("e:"+(""+a+"."+b))};d.prototype.on_entity_version=function(a,b,h){var j,m,p;console.log(""+this.name+": on_entity_version("+a+", "+b+", "+h+")");j=a!=null?this.jd.deepCopy(a):null;p=this.initialized===false&&this.cb_ni!=null?this.cb_ni:this.cb_n;if(b in this.data.store&&
"last"in this.data.store[b]&&this.jd.entries(this.data.store[b].last)){j=this.jd.deepCopy(this.data.store[b].last);p(b,j,null);this.notify_index[b]=true;return this._check_update(b)}else if(b in this.data.store&&h<this.data.store[b].version)return this.cb_nv(b,j,h);else{b in this.data.store||(this.data.store[b]={});this.data.store[b].id=b;this.data.store[b].object=a;this.data.store[b].version=parseInt(h);p(b,j,h);this.notify_index[b]=true;a=0;b=this.notify_index;for(m in b)k.call(b,m)&&this.notify_index[m]===
false&&a++;if(a===0&&this.index_request===false)return this._index_loaded()}};d.prototype._index_loaded=function(){console.log(""+this.name+": index loaded, initialized: "+this.initialized);this.initialized===false&&this.cb_r();this.initialized=true;console.log(""+this.name+": retrieve changes from index loaded");return this.retrieve_changes()};d.prototype._notify_client=function(a,b,h,j,m){var p,q,s,w,v,u;console.log(""+this.name+": _notify_client("+a+", "+b+", "+h+", "+JSON.stringify(j)+")");if(this.cb_l==
null){console.log(""+this.name+": no get callback, notifying without transform");this.cb_n(a,b,m)}else{p=this.cb_l(a);q=null;u=[];if(this.jd.typeOf(p)==="array"){s=p[2];w=p[1];p=p[0];if(q=this.s._captureCursor(s)){u[0]=q.startOffset;if("endOffset"in q)u[1]=q.endOffset}}if(p!=null&&h!=null){v=this.jd.object_diff(h,p);console.log("client/server version diff: "+JSON.stringify(v));if(this.jd.entries(v)===0){console.log("local diff 0 entries");j=j;b=h}else{console.log("o_diff");console.log(v);console.log("orig_object");
console.log(h);console.log("c_object");console.log(p);console.log("client modified doing transform");j=this.jd.transform_object_diff(v,j,h);b=b}if(q){b=this.jd.apply_object_diff_with_offsets(b,j,w,u);if(s!=null&&"value"in s)s.value=b[w];q.startOffset=u[0];if(u.length>1){q.endOffset=u[1];if(q.startOffset>=q.endOffset)q.collapsed=true}this.s._restoreCursor(s,q)}else{console.log("in regular apply_object_diff");console.log("t_object");console.log(b);console.log("t_diff");console.log(j);b=this.jd.apply_object_diff(b,
j)}return this.cb_n(a,b,m)}else return b?this.cb_n(a,b,m):this.cb_n(a,null,null)}};d.prototype._check_update=function(a){var b,h,j,m,p;console.log(""+this.name+": _check_update("+a+")");if(!(a in this.data.store))return false;h=this.data.store[a];if(h.change){a=false;p=this.data.send_queue;j=0;for(m=p.length;j<m;j++){b=p[j];if(b.id===h.change.id&&b.ccid===h.change.ccid)a=true}if(!a){this._queue_change(h.change);return true}return false}if(h.check!=null)return false;if("last"in h&&this.jd.equals(h.object,
h.last)){delete h.last;this._remove_entity(a);return false}b=this._make_change(a);if(b!=null){h.change=b;this._queue_change(b)}else this._remove_entity(a);return true};d.prototype.update=function(a,b){var h,j,m,p,q;if(arguments.length===1)if(this.cb_l!=null){b=this.cb_l(a);if(this.jd.typeOf(b)==="array")b=b[0]}else throw Error("missing 'local' callback");console.log(""+this.name+": update("+a+")");if(a==null&&b==null)return false;if(a!=null){if(a.length===0||a.indexOf("/")!==-1)return false}else a=
this.uuid();a in this.data.store||(this.data.store[a]={id:a,object:{},version:null,change:null,check:null});j=this.data.store[a];j.last=this.jd.deepCopy(b);j.modified=this.s._time();this._save_entity(a);q=this.data.send_queue;m=0;for(p=q.length;m<p;m++){h=q[m];if(String(a)===h.id){console.log(""+this.name+": update("+a+") found pending change, aborting");return null}}j.check!=null&&clearTimeout(j.check);j.check=setTimeout(function(s){return function(w,v){return function(){v.check=null;v.change=s._make_change(w);
delete v.last;s._save_entity(w);return s._queue_change(v.change)}}}(this)(a,j),this.options.update_delay);return a};d.prototype._make_change=function(a){var b,h,j;j=this.data.store[a];h={id:String(a),ccid:this.uuid()};if(this.initialized)if(this.cb_l!=null){b=this.cb_l(a);if(this.jd.typeOf(b)==="array")b=b[0]}else if("last"in j)b=j.last;else return null;else if("last"in j)b=j.last;else return null;if(j.version!=null)h.sv=j.version;if(b===null&&j.version!=null){h.o="-";console.log(""+this.name+": deletion requested for "+
a)}else if(b!=null&&j.object!=null){h.o="M";if("sendfull"in j){h.d=this.jd.deepCopy(b);delete j.sendfull}else{h.v=this.jd.object_diff(j.object,b);if(this.jd.entries(h.v)===0)h=null}}else h=null;return h};d.prototype._queue_change=function(a){if(a!=null){console.log("_queue_change("+a.id+":"+a.ccid+"): sending");this.data.send_queue.push(a);this.send("c:"+JSON.stringify(a));this._check_pending();this.data.send_queue_timer!=null&&clearTimeout(this.data.send_queue_timer);return this.data.send_queue_timer=
setTimeout(this._send_changes,this._send_backoff)}};d.prototype._send_changes=function(){var a,b,h,j;if(this.data.send_queue.length===0){console.log(""+this.name+": send_queue empty, done");this.data.send_queue_timer=null}else{if(this.s.connected){j=this.data.send_queue;b=0;for(h=j.length;b<h;b++){a=j[b];console.log(""+this.name+": sending change: "+JSON.stringify(a));this.send("c:"+JSON.stringify(a))}}else console.log(""+this.name+": _send_changes: not connected");this._send_backoff*=2;if(this._send_backoff>
this._backoff_max)this._send_backoff=this._backoff_max;return this.data.send_queue_timer=setTimeout(this._send_changes,this._send_backoff)}};d.prototype.retrieve_changes=function(){console.log(""+this.name+": requesting changes since cv:"+this.data.last_cv);this.send("cv:"+this.data.last_cv)};d.prototype.on_changes=function(a){var b,h,j,m,p,q,s,w,v,u,r,x,B;h=[];w=false;this._send_backoff=this._backoff_min;console.log(""+this.name+": on_changes(): response=");console.log(a);v=0;for(r=a.length;v<r;v++){b=
a[v];j=b.id;console.log(""+this.name+": processing id="+j);m=[];B=this.data.send_queue;u=0;for(x=B.length;u<x;u++){s=B[u];if(b.clientid===this.clientid&&j===s.id){b.local=true;m.push(s);h.push(j)}}s=0;for(u=m.length;s<u;s++){q=m[s];this.data.store[q.id].change=null;this._save_entity(q.id);this.data.send_queue=function(){var z,I,J,E;J=this.data.send_queue;E=[];z=0;for(I=J.length;z<I;z++){p=J[z];p!==q&&E.push(p)}return E}.call(this)}m.length>0&&this._check_pending();if("error"in b)switch(b.error){case 412:console.log(""+
this.name+": on_changes(): empty change, dont check");j=h.indexOf(b.id);j>-1&&h.splice(j,1);break;case 409:console.log(""+this.name+": on_changes(): duplicate change, ignoring");break;case 405:console.log(""+this.name+": on_changes(): bad version");if(b.id in this.data.store)this.data.store[b.id].version=null;w=true;break;case 440:console.log(""+this.name+": on_change(): bad diff, sending full object");this.data.store[j].sendfull=true;break;default:console.log(""+this.name+": error for last change, reloading");
if(b.id in this.data.store)this.data.store[b.id].version=null;w=true}else{m=b.o;if(m==="-"){delete this.data.store[j];this._remove_entity(j);"local"in b||this._notify_client(b.id,null,null,null,null)}else if(m==="M"){m=this.data.store[j];if("sv"in b&&m!=null&&m.version!=null&&m.version===b.sv||!("sv"in b)||b.ev===1){if(m==null){this.data.store[j]={id:j,object:{},version:null,change:null,check:null};m=this.data.store[j]}j=this.jd.deepCopy(m.object);m.object=this.jd.apply_object_diff(m.object,b.v);
m.version=b.ev;m=this.jd.deepCopy(m.object);"local"in b||this._notify_client(b.id,m,j,b.v,b.ev)}else if(m!=null&&m.version!=null&&b.ev<=m.version)console.log(""+this.name+": old or duplicate change received, ignoring, change.ev="+b.ev+", s_data.version:"+m.version);else{m!=null?console.log(""+this.name+": version mismatch couldnt apply change, change.ev:"+b.ev+", s_data.version:"+m.version):console.log(""+this.name+": version mismatch couldnt apply change, change.ev:"+b.ev+", s_data null");if(m!=
null)this.data.store[j].version=null;w=true}}else console.log(""+this.name+": no operation found for change");if(!w){this.data.last_cv=b.cv;this._save_meta();console.log(""+this.name+": checkpoint cv="+this.data.last_cv+" ccid="+this.data.ccid)}}}if(w){console.log(""+this.name+": reload needed, refreshing store");setTimeout(function(z){return function(){return z._refresh_store()}}(this))}else{a=function(z){return function(I){return setTimeout(function(){return z._check_update(I)},z.options.update_delay)}}(this);
w=0;for(v=h.length;w<v;w++){j=h[w];a(j)}}};d.prototype.pending=function(){var a,b,h,j,m;b=function(){var p,q,s,w;s=this.data.send_queue;w=[];p=0;for(q=s.length;p<q;p++){a=s[p];w.push(a.id)}return w}.call(this);console.log(""+this.name+": pending: "+JSON.stringify(b));j=this.data.send_queue;m=[];b=0;for(h=j.length;b<h;b++){a=j[b];m.push(a.id)}return m};d.prototype._check_pending=function(){var a,b,h,j,m,p;if(this.cb_np!=null){a=this.pending();b=true;if(this._last_pending){b=false;if(this._last_pending.length===
a.length){p=this._last_pending;j=0;for(m=p.length;j<m;j++){h=p[j];if(a.indexOf(h)===-1)b=true}}else b=true}if(b){this._last_pending=a;return this.cb_np(a)}}};return d}();f=function(){function d(a,b){var h,j,m;this.app_id=a;this.options=b;this._restoreCursor=c(this._restoreCursor,this);this._captureCursor=c(this._captureCursor,this);this._sock_message=c(this._sock_message,this);this._sock_hb_check=c(this._sock_hb_check,this);this._sock_closed=c(this._sock_closed,this);this._sock_opened=c(this._sock_opened,
this);this._sock_connect=c(this._sock_connect,this);this.synced=c(this.synced,this);this.send=c(this.send,this);this.stop=c(this.stop,this);this.start=c(this.start,this);this.on=c(this.on,this);this.bucket=c(this.bucket,this);this.bversion=2014030401;this.jd=new jsondiff;this.dmp=this.jd.dmp;this.auth_token=null;this.options=this.options||{};this.options.app_id=this.app_id;this.sock_opts={debug:false};if("sockjs"in this.options){m=this.options.sockjs;for(h in m)if(k.call(m,h)){j=m[h];this.sock_opts[h]=
j}}"host"in this.options||(this.options.host="api.simperium.com");"port"in this.options||(this.options.port=80);if("token"in this.options)this.auth_token=this.options.token;h=this.options.host.indexOf("simperium.com")!==-1?"https":"http";this.buckets={};this.channels=0;"update_delay"in this.options||(this.options.update_delay=0);"page_delay"in this.options||(this.options.page_delay=0);this.options.prefix="sock/1/"+this.app_id;this.options.port=parseInt(this.options.port);this.sock_url=this.options.port!==
80&&this.options.port!==443?""+h+"://"+this.options.host+":"+this.options.port+"/"+this.options.prefix:""+h+"://"+this.options.host+"/"+this.options.prefix;this.stopped=false;this._sock_backoff=3E3;this._sock_hb=1;this._sock_connect()}d.prototype.lowerstrip=function(a){a=a.toLowerCase();return String.prototype.trim!=null?a.trim():a.replace(/^\s+|\s+$/g,"")};d.prototype._time=function(){var a;a=new Date;return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),
a.getUTCSeconds(),a.getUTCMilliseconds())/1E3};d.prototype.supports_html5_storage=function(){try{return"localStorage"in window&&window.localStorage!==null}catch(a){return false}};d.prototype.bucket=function(a,b){var h;a=this.lowerstrip(a);b=b||{};b.n=this.channels++;h=new e(this,a,b);return this.buckets[b.n]=h};d.prototype.on=function(a,b,h){return this.buckets[a].on(b,h)};d.prototype.start=function(){var a,b,h;this.stopped=false;b=this.buckets;h=[];for(a in b)if(k.call(b,a)){e=b[a];h.push(e.start())}return h};
d.prototype.stop=function(){this.stopped=true;if(this.sock!=null)return this.sock.close()};d.prototype.send=function(a){return this.sock.send(a)};d.prototype.synced=function(){var a,b;b=this.buckets;for(a in b)if(k.call(b,a)){e=b[a];if(e.pending().length>0)return false}return true};d.prototype._sock_connect=function(){console.log("simperium: connecting to "+this.sock_url);this.authorized=this.connected=false;this.sock=new SockJS(this.sock_url,void 0,this.sock_opts);this.sock.onopen=this._sock_opened;
this.sock.onmessage=this._sock_message;return this.sock.onclose=this._sock_closed};d.prototype._sock_opened=function(){var a,b,h;this._sock_backoff=3E3;this.connected=true;this._sock_hb_timer=setTimeout(this._sock_hb_check,2E4);b=this.buckets;h=[];for(a in b)if(k.call(b,a)){e=b[a];e.started?h.push(e.start()):h.push(void 0)}return h};d.prototype._sock_closed=function(){var a,b;this.connected=false;b=this.buckets;for(a in b)if(k.call(b,a)){e=b[a];e.authorized=false}console.log("simperium: sock js closed");
if(this._sock_backoff<4E3)this._sock_backoff+=1;else this._sock_backoff=15E3;if(this._sock_hb_timer){clearTimeout(this._sock_hb_timer);this._sock_hb_timer=null}if(!this.stopped)return setTimeout(this._sock_connect,this._sock_backoff)};d.prototype._sock_hb_check=function(){var a;a=(new Date).getTime()-this._sock_msg_time;if(this.connected!==false){if(a>4E4){console.log("simperium: force conn close");this.sock.close()}else if(a>15E3){console.log("simperium: send hb "+this._sock_hb);this.sock.send("h:"+
this._sock_hb)}return this._sock_hb_timer=setTimeout(this._sock_hb_check,2E4)}};d.prototype._sock_message=function(a){var b,h;this._sock_msg_time=(new Date).getTime();b=a.data;h=b.indexOf(":");a=null;if(h===1&&b.charAt(0)==="h")this._sock_hb=b.substr(2);else{try{a=parseInt(b.substr(0,h));b=b.substr(h+1)}catch(j){a=null}if(a!==null)if(a in this.buckets)return this.buckets[a].on_data(b)}};d.prototype._captureCursor=function(){};d.prototype._captureCursor=function(a){if("activeElement"in a&&!a.activeElement)return null;
var b=this.dmp.Match_MaxBits/2,h=a.value,j={};if("selectionStart"in a){try{var m=a.selectionStart,p=a.selectionEnd}catch(q){return null}j.startPrefix=h.substring(m-b,m);j.startSuffix=h.substring(m,m+b);j.startOffset=m;j.collapsed=m==p;if(!j.collapsed){j.endPrefix=h.substring(p-b,p);j.endSuffix=h.substring(p,p+b);j.endOffset=p}}else{for(m=a;m.parentNode;)m=m.parentNode;if(!m.selection||!m.selection.createRange)return null;h=m.selection.createRange();if(h.parentElement()!=a)return null;m=m.body.createTextRange();
j.collapsed=h.text=="";m.moveToElementText(a);if(!j.collapsed){m.setEndPoint("EndToEnd",h);j.endPrefix=m.text;j.endOffset=j.endPrefix.length;j.endPrefix=j.endPrefix.substring(j.endPrefix.length-b)}m.setEndPoint("EndToStart",h);j.startPrefix=m.text;j.startOffset=j.startPrefix.length;j.startPrefix=j.startPrefix.substring(j.startPrefix.length-b);m.moveToElementText(a);m.setEndPoint("StartToStart",h);j.startSuffix=m.text.substring(0,b);if(!j.collapsed){m.setEndPoint("StartToEnd",h);j.endSuffix=m.text.substring(0,
b)}}if("scrollTop"in a){j.scrollTop=a.scrollTop/a.scrollHeight;j.scrollLeft=a.scrollLeft/a.scrollWidth}return j};d.prototype._restoreCursor=function(){};d.prototype._restoreCursor=function(a,b){this.dmp.Match_Distance=1E3;this.dmp.Match_Threshold=0.9;var h=this.dmp.Match_MaxBits/2,j=a.value,m=b.startPrefix+b.startSuffix,p,q=this.dmp.match_main(j,m,b.startOffset-h);if(q!==null){p=j.substring(q,q+m.length);m=this.dmp.diff_main(m,p,false);q+=this.dmp.diff_xIndex(m,b.startPrefix.length)}var s=null;if(!b.collapsed){m=
b.endPrefix+b.endSuffix;s=this.dmp.match_main(j,m,b.endOffset-h);if(s!==null){p=j.substring(s,s+m.length);m=this.dmp.diff_main(m,p,false);s+=this.dmp.diff_xIndex(m,b.endPrefix.length)}}if(q===null&&s!==null)q=s;else if(q===null&&s===null)q=b.startOffset;if(s===null)s=q;if("selectionStart"in a){a.selectionStart=q;a.selectionEnd=s}else{for(h=a;h.parentNode;)h=h.parentNode;if(!h.selection||!h.selection.createRange)return;j=a.value.substring(0,q);j=j.replace(/\r\n/g,"\n").length;h=h.body.createTextRange();
h.moveToElementText(a);h.collapse(true);h.moveStart("character",j);if(!b.collapsed){j=a.value.substring(q,s);q=j.replace(/\r\n/g,"\n").length;h.moveEnd("character",q)}h.select()}if("scrollTop"in b){a.scrollTop=b.scrollTop*a.scrollHeight;a.scrollLeft=b.scrollLeft*a.scrollWidth}};return d}();window.Simperium=f;e.prototype.on=e.prototype.on;e.prototype.start=e.prototype.start;e.prototype.load_versions=e.prototype.load_versions;e.prototype.pending=e.prototype.pending;f.prototype.on=f.prototype.on;f.prototype.start=
f.prototype.start;f.prototype.bucket=f.prototype.bucket;f.prototype.synced=f.prototype.synced}).call(this);
