#server_port: 9191
relative_permalinks: false
url: http://fluentglobe.com
img_url: http://fluentglobe.com/images
a_url: http://a.fluentglobe.com
title: Fluent Globe
description: People at Fluent Globe guide you when learning a language on your own so you feel motivated and reminded of your goal.
author: Henrik Vendelbo
email: people@fluentglobe.com
domain: fluentglobe.com
analytics_id: UA-22749258-6
analytics_version: 5.2.6
facebook_page: FluentGlobe
twitter_id: fluentglobe
gplus_page_id: 104383519689106528970
linkedin_company_id: 4998340
facebook_app_id: 266550166850505
facebook_app_secret: 15032455e1aded282721cca42580a328
personal_facebook_app_id: 176178315769197

fluentbook_simperium_app_id: humans-crusts-58a
fluentbook_simperium_api_key: 611297d26ac44e40976e107de6f7d492
website_simperium_app_id: eights-commitments-4c4
website_simperium_api_key: de9c504d6f174fe4b8cecd3615583324
website_simperium_readonly_key: 02409ad057b74eb685f8d9f783484970

seil-ibook-url: portuguese-for-travelers/id568515833

exclude:
- fluent-globe-4461545
- Jakefile
- test.html
- README.mdown
- Gruntfile.js
- bower.json
- package.json
- .bowerrc
- node_modules
- components


#- images 
#- fonts
fb_admins: 739870725
lsi: false
highlighter: true
markdown: redcarpet
permalink: pretty
maruku:
  use_tex: false
  use_divs: false
  png_dir: images/latex
  png_url: /images/latex
safe: false
lessc: lessc

redcarpet:
  extensions: 
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - tables
  - quote
  - with_toc_data

concatenate:
- js/prefix|modernizr|essential.js
- js/uri|impl|form|app.js
- js/uri+impl+form+app.js
# - js/memory.js
#- js/prefix+modernizr+essential.min.js
