#server_port: 9191
url: http://fluentglobe.com
img_url: http://fluentglobe.com/images
a_url: http://a.fluentglobe.com
title: Fluent Globe
description: People at Fluent Globe guide you when learning a language on your own so you feel motivated and reminded of your goal.
email: people@fluentglobe.com
domain: fluentglobe.com
analytics_id: UA-22749258-6
# facebook_page: fluentglobe
twitter_id: fluentglobe
gplus_page_id: 104383519689106528970
linkedin_company_id: 4998340

seil-ibook-url: portuguese-for-travelers/id568515833

exclude:
- fluent-globe-4461545
- _site
- test.html
- _site
- Jakefile
- test.html
- README.mdown
- Gruntfile.js
- bower.json
- package.json
- .bowerrc
- node_modules
- bower_components


#- images 
#- fonts

lsi: false
pygments: true
markdown: redcarpet
permalink: pretty
maruku:
  use_tex: false
  use_divs: false
  png_dir: images/latex
  png_url: /images/latex
safe: false
lessc: lessc

redcarpet:
  extensions: 
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - tables
  - quote
  - with_toc_data

concatenate:
- js/prefix|modernizr|essential.js
- js/uri|impl|form|app.js
- js/uri+impl+form+app.js
# - js/memory.js
#- js/prefix+modernizr+essential.min.js
